package sqlpragmas

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TODO.md P0: "when changing pragmasFor, update unit + integration tests in the
// same PR". The reason that rule exists is that pragmasFor is a table of
// literals with no natural failure mode — bump a cache size or drop a
// journal_mode line and every test still passes, because the tests assert the
// pragmas they were told to assert, not the ones the function emits.
//
// The golden file closes that. It is the complete emitted preset for every
// (profile × host class) pair, so ANY edit to pragmasFor — a changed value, a
// reordered statement, an added or removed pragma, a new profile, a new host
// class — fails this test until the author regenerates the golden and reads the
// diff. Reading the diff is the point: it is the review artifact the prose rule
// was asking for.
//
// Regenerate with:
//
//	go test ./internal/sqlpragmas/ -run TestPragmasFor_Golden -update

var updateGolden = flag.Bool("update", false, "rewrite testdata/pragmas.golden from the current pragmasFor output")

const goldenPath = "testdata/pragmas.golden"

func TestPragmasFor_WhenPresetsChange_ShouldMatchGolden(t *testing.T) {
	got := renderPragmaMatrix(t)

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("golden updated: %s", goldenPath)
		return
	}

	wantBytes, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (regenerate with -update): %v", err)
	}
	want := strings.ReplaceAll(string(wantBytes), "\r\n", "\n")

	if got == want {
		return
	}

	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	var diff []string
	for i := 0; i < len(gotLines) || i < len(wantLines); i++ {
		g, w := "", ""
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if g != w {
			diff = append(diff, "  line "+itoa(i+1)+":\n    golden: "+w+"\n    actual: "+g)
		}
	}

	t.Errorf("pragmasFor output no longer matches %s:\n%s\n\n"+
		"If the change is intended: regenerate with `go test ./internal/sqlpragmas/ -run TestPragmasFor_Golden -update`, "+
		"read the diff, and update the per-profile assertions in pragmas_test.go / pragma_integration_test.go and "+
		"Docs/architecture/sqlpragmas/IMPLEMENTED_SPEC.md in the same change.",
		goldenPath, strings.Join(diff, "\n"))
}

// renderPragmaMatrix emits every profile's preset at every host class.
//
// Both dimensions are enumerated from the constants declared in the package
// source, not from a hand-written list here, so a newly declared profile or
// host class shows up in the golden automatically. Both const blocks start at
// iota 0 and are contiguous, so declaration index is the constant's value.
func renderPragmaMatrix(t *testing.T) string {
	t.Helper()

	pkgDir := packageDir(t)
	profileNames := constantsOfType(t, pkgDir, "PragmaProfile")
	hostNames := constantsOfType(t, pkgDir, "HostClass")

	if len(profileNames) == 0 || len(hostNames) == 0 {
		t.Fatal("golden scanner found no profile or host-class constants")
	}

	var b strings.Builder
	b.WriteString("# Generated by TestPragmasFor_WhenPresetsChange_ShouldMatchGolden -update.\n")
	b.WriteString("# Every PRAGMA this package emits, per profile and host class, in emission order.\n")

	for hi, hostName := range hostNames {
		host := HostClass(hi)
		// The declared constant must agree with String(); if someone renames
		// one without the other the golden would silently mislabel a section.
		if host.String() != strings.ToLower(strings.TrimPrefix(hostName, "Host")) {
			t.Fatalf("host class %s (value %d) stringifies as %q — golden section labels would be wrong", hostName, hi, host.String())
		}
		for pi, profileName := range profileNames {
			profile := PragmaProfile(pi)
			if profile.String() != strings.TrimPrefix(profileName, "Profile") {
				t.Fatalf("profile %s (value %d) stringifies as %q — golden section labels would be wrong", profileName, pi, profile.String())
			}
			b.WriteString("\n[" + hostName + " / " + profileName + "]\n")
			for _, p := range pragmasForHost(profile, host) {
				b.WriteString(p + "\n")
			}
		}
	}
	return b.String()
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}
