// Package main implements the codeNERD CLI commands.
// This file contains dream state and advanced commands.
package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"

	"codenerd/internal/autopoiesis"
	"codenerd/internal/config"
	"codenerd/internal/core"
	"codenerd/internal/logging"
	coresys "codenerd/internal/system"
	"codenerd/internal/types"
	"codenerd/internal/usage"

	"github.com/spf13/cobra"
)

// =============================================================================
// DREAM STATE & ADVANCED COMMANDS
// =============================================================================

// dreamCmd runs dream state multi-agent consultation
var dreamCmd = &cobra.Command{
	Use:   "dream <scenario>",
	Short: "Run dream state multi-agent consultation",
	Long: `Consults multiple shard agents about a hypothetical scenario.
Each agent provides their perspective without executing any changes.
Equivalent to typing "what if <scenario>" or using /dream in the TUI.

Example:
  nerd dream "we migrated from REST to GraphQL"
  nerd dream "implementing caching with Redis"`,
	Args: cobra.MinimumNArgs(1),
	RunE: runDreamState,
}

// shadowCmd runs shadow mode simulation
var shadowCmd = &cobra.Command{
	Use:   "shadow <action>",
	Short: "Simulate an action without executing",
	Long: `Runs a shadow simulation showing what would happen.
No actual changes are made - purely descriptive output.
Equivalent to /shadow in the TUI.

Example:
  nerd shadow "delete all test files"
  nerd shadow "refactor the auth module"`,
	Args: cobra.MinimumNArgs(1),
	RunE: runShadowSimulation,
}

// whatifCmd runs counterfactual query
var whatifCmd = &cobra.Command{
	Use:   "whatif <change>",
	Short: "Run counterfactual analysis",
	Long: `Analyzes what would happen if a change were made.
Uses the Mangle kernel to derive implications.
Equivalent to /whatif in the TUI.

Example:
  nerd whatif "we removed the database connection pooling"
  nerd whatif "error handling was centralized"`,
	Args: cobra.MinimumNArgs(1),
	RunE: runWhatIf,
}

// logicCmd shows kernel facts
var logicCmd = &cobra.Command{
	Use:   "logic [predicate]",
	Short: "Show Mangle kernel facts",
	Long: `Displays facts currently in the Mangle kernel.
Optionally filter by predicate name.
Equivalent to /logic in the TUI.

Example:
  nerd logic              # Show all facts
  nerd logic user_intent  # Show only user_intent facts
  nerd logic shard_result # Show shard results`,
	RunE: runLogicQuery,
}

// agentsCmd lists available agents
var agentsCmd = &cobra.Command{
	Use:   "agents",
	Short: "List available shard agents",
	Long: `Shows all registered shard agents with their capabilities.
Includes both ephemeral and persistent specialists.
Equivalent to /agents in the TUI.`,
	RunE: runAgentsList,
}

// toolCmd manages generated tools
var toolCmd = &cobra.Command{
	Use:   "tool <list|run|info|generate> [args]",
	Short: "Manage generated tools (Ouroboros)",
	Long: `Manage tools generated by the Ouroboros Loop.

Subcommands:
  list              - List all generated tools
  run <name> [in]   - Execute a tool with optional input
  info <name>       - Show tool details and source
  generate <desc>   - Generate a new tool from description

Examples:
  nerd tool list
  nerd tool run json-validator '{"test": 123}'
  nerd tool generate "a tool that validates JSON syntax"`,
	Args: cobra.MinimumNArgs(1),
	RunE: runToolCommand,
}

// jitCmd shows JIT compiler status
var jitCmd = &cobra.Command{
	Use:   "jit",
	Short: "Show JIT prompt compiler status",
	Long: `Displays the JIT Prompt Compiler's current state.
Shows loaded atoms, token budget, and compilation stats.
Equivalent to /jit in the TUI.`,
	RunE: runJITStatus,
}

// runDreamState executes dream state consultation
func runDreamState(cmd *cobra.Command, args []string) error {
	// Honour --timeout rather than a hardcoded 5 minutes.
	//
	// Observed live: 22 agents consulted, every one failing "context deadline
	// exceeded", and the command still printed "Dream state consultation
	// complete" and exited 0. Three separate faults produced that, all fixed
	// here — the flat 5-minute ceiling (identical to the bug already fixed in
	// runToolCommand below), a strictly sequential fan-out sharing that one
	// budget, and a success message that never consulted the results.
	dreamTimeout := timeout
	if dreamTimeout <= 0 {
		dreamTimeout = 25 * time.Minute
	}
	ctx, cancel := context.WithTimeout(context.Background(), dreamTimeout)
	defer cancel()

	scenario := strings.Join(args, " ")

	fmt.Printf("🌙 Dream State Consultation\n")
	fmt.Printf("📝 Scenario: %s\n", scenario)
	fmt.Println(strings.Repeat("─", 60))

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// Add usage tracker
	if cortex.UsageTracker != nil {
		ctx = usage.NewContext(ctx, cortex.UsageTracker)
	}

	// Get available shards
	shards := cortex.ShardManager.ListAvailableShards()

	// Consult each shard in dream mode
	dreamCtx := &types.SessionContext{DreamMode: true}
	prompt := fmt.Sprintf("Dream Mode Consultation:\n\nScenario: %s\n\nProvide your perspective on this hypothetical. Do NOT execute any actions - only describe what you would do and the implications.", scenario)

	// Consult concurrently.
	//
	// Sequentially, 22 consultations shared one deadline: cortex boot ate the
	// first half-minute, each agent consumed what was left in turn, and every
	// agent after the budget ran out failed instantly without making a single
	// call. Same shape as the init doc-triage defect (196 sequential batches
	// against a 25-minute timeout). The pool is deliberately modest — the
	// APIScheduler is global, so a wider fan-out just queues behind the same
	// rate limit.
	type dreamResult struct {
		index    int
		name     string
		shardTyp types.ShardType
		response string
		err      error
	}

	// Indices into shards, so the concrete ShardInfo type stays unnamed here.
	consultable := make([]int, 0, len(shards))
	skippedImage := 0
	for i, shard := range shards {
		if shard.Type == types.ShardTypeSystem {
			continue // internal/system shards have no perspective to offer
		}
		// The image generator is registered under seven aliases
		// (internal/shards/registration.go:216), and ListAvailableShards
		// returns each as a separate shard. Dream was therefore sending a
		// text-consultation prompt to the same image model seven times per
		// run, collecting seven HTTP 400s — measured live: 7 of 8 failures in
		// a 12-minute run were exactly this, the eighth a real timeout.
		// An image model has no perspective on a hypothetical to begin with.
		if config.IsImageShardType(shard.Name) {
			skippedImage++
			continue
		}
		consultable = append(consultable, i)
	}
	// Announce the count actually consulted, not the raw registry size. It
	// said "Consulting 22 agents" while consulting 9, so the error tally never
	// added up to the announced total and the gap looked like silent drops.
	fmt.Printf("🤖 Consulting %d agents", len(consultable))
	if skipped := len(shards) - len(consultable); skipped > 0 {
		fmt.Printf(" (%d skipped: %d system, %d image-generation aliases)",
			skipped, skipped-skippedImage, skippedImage)
	}
	fmt.Println("...")
	fmt.Println()

	const dreamConcurrency = 6
	results := make([]dreamResult, len(consultable))
	sem := make(chan struct{}, dreamConcurrency)
	var wg sync.WaitGroup

	for slot, shardIdx := range consultable {
		wg.Add(1)
		go func(slot, shardIdx int) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			shard := shards[shardIdx]
			// Dream mode = low priority (background speculation)
			result, err := cortex.SpawnTaskWithContext(ctx, shard.Name, prompt, dreamCtx, types.PriorityLow)
			results[slot] = dreamResult{index: slot, name: shard.Name, shardTyp: shard.Type, response: result, err: err}
		}(slot, shardIdx)
	}
	wg.Wait()

	succeeded, failed := 0, 0
	for i, r := range results {
		fmt.Printf("[%d] %s (%s)...\n", i+1, r.name, r.shardTyp)
		if r.err != nil {
			failed++
			fmt.Printf("   ❌ Error: %v\n\n", r.err)
			continue
		}
		succeeded++
		fmt.Printf("   ✓ Response:\n")
		for line := range strings.SplitSeq(truncateResponse(r.response, 500), "\n") {
			fmt.Printf("     %s\n", line)
		}
		fmt.Println()
	}

	fmt.Println(strings.Repeat("─", 60))

	// Report the outcome the run actually had.
	summary, err := dreamSummary(succeeded, failed, dreamTimeout, ctx.Err() != nil)
	fmt.Println(summary)
	if err != nil {
		return err
	}

	return nil
}

// dreamSummary renders the outcome line and reports whether the consultation
// failed outright.
//
// Split out from runDreamState so the all-failed branch can be pinned by a
// test. It cannot be reached live any more: the concurrent fan-out completes
// several agents even on a 32-second budget, which is exactly why the original
// bug survived — the failure mode only appeared under a deadline the
// sequential version imposed on itself, and the unconditional "✅ complete"
// then hid it.
func dreamSummary(succeeded, failed int, budget time.Duration, deadlineExpired bool) (string, error) {
	switch {
	case succeeded == 0 && failed > 0:
		msg := fmt.Sprintf("❌ Dream state consultation FAILED: all %d agents errored", failed)
		if deadlineExpired {
			msg += fmt.Sprintf("\n   The %s budget expired. Raise it with --timeout.", budget)
		}
		return msg, fmt.Errorf("dream consultation failed: all %d agents errored", failed)
	case failed > 0:
		return fmt.Sprintf("⚠️  Dream state consultation partial: %d succeeded, %d failed", succeeded, failed), nil
	case succeeded == 0:
		// No consultable agents at all: not a success, and silently claiming
		// one would repeat the defect in a different shape.
		return "⚠️  Dream state consultation ran no agents (none available to consult)", nil
	default:
		return fmt.Sprintf("✅ Dream state consultation complete: %d agents responded", succeeded), nil
	}
}

// runShadowSimulation runs shadow mode
func runShadowSimulation(cmd *cobra.Command, args []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	action := strings.Join(args, " ")

	fmt.Printf("👻 Shadow Mode Simulation\n")
	fmt.Printf("🎯 Action: %s\n", action)
	fmt.Println(strings.Repeat("─", 60))

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// Use coder shard in shadow mode
	shadowCtx := &types.SessionContext{DreamMode: true}
	prompt := fmt.Sprintf("SHADOW MODE - Describe what would happen without executing:\n\n%s\n\nList the files that would be affected, changes that would be made, and potential risks. Do NOT actually make any changes.", action)

	// Shadow mode = normal priority (user CLI command but speculative)
	result, err := cortex.SpawnTaskWithContext(ctx, "coder", prompt, shadowCtx, types.PriorityNormal)
	if err != nil {
		return fmt.Errorf("shadow simulation failed: %w", err)
	}

	fmt.Println("📋 Simulation Result:")
	fmt.Println(result)

	return nil
}

// runWhatIf runs counterfactual analysis.
// Kernel implications are the deterministic, always-complete result. Optional
// LLM elaboration uses a short direct Complete call — never SpawnTask(researcher),
// which previously hung after the first kernel line when the JIT spawn path stalled.
func runWhatIf(cmd *cobra.Command, args []string) error {
	// Overall budget: boot + kernel + optional LLM elaboration.
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	change := strings.Join(args, " ")

	fmt.Printf("🔮 What-If Analysis\n")
	fmt.Printf("❓ Change: %s\n", change)
	fmt.Println(strings.Repeat("─", 60))

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// Assert the hypothetical to kernel
	hypFact := core.Fact{
		Predicate: "hypothetical",
		Args:      []any{change},
	}
	if err := cortex.Kernel.Assert(hypFact); err != nil {
		logging.KernelWarn("failed to assert hypothetical fact: %v", err)
	}

	// Query implications
	implications, _ := cortex.Kernel.Query("derives_from_hypothetical")

	fmt.Println("📊 Kernel Implications:")
	if len(implications) > 0 {
		for _, imp := range implications {
			fmt.Printf("   - %s\n", imp.String())
		}
	} else {
		fmt.Println("   (no derived implications)")
	}
	fmt.Println()

	// Bounded LLM elaboration (optional). Fail soft so the command always exits.
	if cortex.LLMClient == nil {
		fmt.Println("📋 Analysis: (skipped — no LLM client)")
		return nil
	}

	prompt := fmt.Sprintf(
		"Analyze the implications of this hypothetical change in 6-10 bullet points:\n\n%s\n\nCover: affected systems, breakage risk, improvements, and mitigations.",
		change,
	)
	analysisCtx, analysisCancel := context.WithTimeout(ctx, 45*time.Second)
	defer analysisCancel()

	fmt.Println("📋 Analysis:")
	result, err := cortex.LLMClient.Complete(analysisCtx, prompt)
	if err != nil {
		if analysisCtx.Err() != nil {
			fmt.Println("   (analysis timed out; kernel implications above are complete)")
		} else {
			fmt.Printf("   Analysis failed: %v\n", err)
		}
		return nil
	}
	fmt.Println(result)
	return nil
}

// runLogicQuery shows kernel facts
func runLogicQuery(cmd *cobra.Command, args []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	fmt.Printf("🧠 Mangle Kernel Facts\n")

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// With no predicate, show what the kernel holds.
	//
	// The default used to be the literal string "*", which is not a wildcard
	// the kernel understands — it is simply a predicate name nothing matches.
	// So bare `nerd logic` printed "Found 0 facts" on a kernel holding 3,737
	// file_topology and 10,510 symbol_graph facts, and read as an empty brain.
	if len(args) == 0 {
		return printKernelFactSummary(cortex)
	}

	predicate := args[0]
	fmt.Printf("🔍 Query: %s\n", predicate)
	fmt.Println(strings.Repeat("─", 60))

	// Query facts
	facts, err := cortex.Kernel.Query(predicate)
	if err != nil {
		return fmt.Errorf("query failed: %w", err)
	}

	fmt.Printf("📊 Found %d facts:\n\n", len(facts))
	for i, fact := range facts {
		if i >= 50 {
			fmt.Printf("... and %d more\n", len(facts)-50)
			break
		}
		fmt.Printf("  %s\n", fact.String())
	}

	return nil
}

// printKernelFactSummary reports which predicates hold facts and how many,
// which is the useful answer to a bare `nerd logic`. Naming a predicate still
// lists its facts.
func printKernelFactSummary(cortex *coresys.Cortex) error {
	fmt.Println("🔍 Summary (pass a predicate to list its facts)")
	fmt.Println(strings.Repeat("─", 60))

	byPredicate, err := cortex.Kernel.QueryAll()
	if err != nil {
		return fmt.Errorf("failed to read kernel facts: %w", err)
	}

	counts := make(map[string]int, len(byPredicate))
	for predicate, facts := range byPredicate {
		counts[predicate] = len(facts)
	}

	if len(counts) == 0 {
		fmt.Println("📊 The kernel holds no facts.")
		fmt.Println("   Run 'nerd scan' to index the workspace.")
		return nil
	}

	type predCount struct {
		name  string
		count int
	}
	ordered := make([]predCount, 0, len(counts))
	total := 0
	for name, count := range counts {
		ordered = append(ordered, predCount{name, count})
		total += count
	}
	sort.Slice(ordered, func(i, j int) bool {
		if ordered[i].count != ordered[j].count {
			return ordered[i].count > ordered[j].count
		}
		return ordered[i].name < ordered[j].name
	})

	fmt.Printf("📊 %d facts across %d predicates:\n\n", total, len(ordered))
	const shown = 25
	for i, pc := range ordered {
		if i >= shown {
			fmt.Printf("\n... and %d more predicates\n", len(ordered)-shown)
			break
		}
		fmt.Printf("  %-40s %7d\n", pc.name, pc.count)
	}

	return nil
}

// runAgentsList lists available agents
func runAgentsList(cmd *cobra.Command, args []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	fmt.Printf("🤖 Available Shard Agents\n")
	fmt.Println(strings.Repeat("─", 60))

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// List shards
	shards := cortex.ShardManager.ListAvailableShards()

	// Group by type
	typeGroups := make(map[types.ShardType][]types.ShardInfo)
	for _, shard := range shards {
		typeGroups[shard.Type] = append(typeGroups[shard.Type], shard)
	}

	typeNames := map[types.ShardType]string{
		types.ShardTypeEphemeral:  "Ephemeral (Type A)",
		types.ShardTypePersistent: "Persistent (Type B)",
		types.ShardTypeUser:       "User-Defined (Type U)",
		types.ShardTypeSystem:     "System (Type S)",
	}

	for shardType, shards := range typeGroups {
		fmt.Printf("\n### %s\n", typeNames[shardType])
		for _, shard := range shards {
			knowledgeStr := ""
			if shard.HasKnowledge {
				knowledgeStr = " [+knowledge]"
			}
			fmt.Printf("  - %s%s\n", shard.Name, knowledgeStr)
		}
	}

	fmt.Printf("\nTotal: %d agents\n", len(shards))
	return nil
}

// runToolCommand handles tool management
func runToolCommand(cmd *cobra.Command, args []string) error {
	if len(args) == 0 {
		fmt.Println("Usage: nerd tool <list|run|info|generate> [args]")
		return nil
	}

	// Honour the documented --timeout flag rather than a hardcoded ceiling.
	//
	// This was 5 minutes flat. `nerd tool generate` runs a whole Ouroboros
	// pipeline behind that one deadline -- detect the need, generate the code
	// via LLM, compile it, register it -- and the codegen call alone routinely
	// exceeds five minutes on a reasoning model. The command advertises
	// `--timeout` in its own help text (default 25m) and then ignored it, so
	// every generation died with a bare "context deadline exceeded" that named
	// neither the real limit nor the flag that was supposed to control it.
	toolCtxTimeout := timeout
	if toolCtxTimeout <= 0 {
		toolCtxTimeout = 25 * time.Minute
	}
	ctx, cancel := context.WithTimeout(context.Background(), toolCtxTimeout)
	defer cancel()

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	subCmd := args[0]
	switch subCmd {
	case "list":
		fmt.Println("🔧 Generated Tools (Ouroboros)")
		fmt.Println(strings.Repeat("─", 60))

		// Prefer the durable Ouroboros registry (survives across CLI process
		// restarts via disk restore). Kernel tool_registered facts alone are
		// session-local and frequently empty after a fresh boot even when
		// tools exist on disk — the live-matrix hollow success.
		seen := map[string]bool{}
		listed := 0
		if cortex.Orchestrator != nil {
			for _, tool := range cortex.Orchestrator.ListTools() {
				if tool.Name == "" || seen[tool.Name] {
					continue
				}
				seen[tool.Name] = true
				listed++
				desc := tool.Description
				if desc != "" {
					fmt.Printf("  - %s: %s\n", tool.Name, desc)
				} else {
					fmt.Printf("  - %s\n", tool.Name)
				}
			}
		}
		// Also surface any kernel-only registrations from this session.
		kernelTools, _ := cortex.Kernel.Query("tool_registered")
		for _, tool := range kernelTools {
			if len(tool.Args) == 0 {
				continue
			}
			name := types.ExtractString(tool.Args[0])
			if name == "" || seen[name] {
				continue
			}
			seen[name] = true
			listed++
			fmt.Printf("  - %s\n", name)
		}
		if listed == 0 {
			fmt.Println("No tools generated yet.")
			fmt.Println("\nUse 'nerd tool generate <description>' to create one.")
		}

	case "run":
		if len(args) < 2 {
			return fmt.Errorf("usage: nerd tool run <name> [input]")
		}
		toolName := args[1]
		toolInput := ""
		if len(args) > 2 {
			toolInput = strings.Join(args[2:], " ")
		}

		fmt.Printf("🔧 Running tool: %s\n", toolName)
		fmt.Println(strings.Repeat("─", 60))

		// Find tool binary path from kernel facts
		var binaryPath string
		allBinaries, _ := cortex.Kernel.Query("tool_binary_path")
		for _, b := range allBinaries {
			if len(b.Args) >= 2 && types.ExtractString(b.Args[0]) == toolName {
				binaryPath = types.ExtractString(b.Args[1])
				break
			}
		}

		if binaryPath == "" {
			return fmt.Errorf("tool '%s' not found. Run 'nerd tool list' to see available tools", toolName)
		}

		// SECURITY FIX: Prevent command injection and path traversal
		// Ensure the binary is executed from the .nerd/tools/.compiled directory
		ws := workspace
		if ws == "" {
			ws, _ = os.Getwd()
		}
		expectedDir := filepath.Join(ws, ".nerd", "tools", ".compiled")

		absExpectedDir, err := filepath.Abs(expectedDir)
		if err != nil {
			return fmt.Errorf("failed to resolve expected tools directory: %w", err)
		}

		absBinaryPath, err := filepath.Abs(binaryPath)
		if err != nil {
			return fmt.Errorf("failed to resolve binary path: %w", err)
		}

		relPath, err := filepath.Rel(absExpectedDir, absBinaryPath)
		if err != nil || strings.HasPrefix(relPath, "..") || relPath == ".." || filepath.IsAbs(relPath) {
			return fmt.Errorf("security error: binary path '%s' is outside expected directory '%s'", binaryPath, expectedDir)
		}

		if _, err := os.Stat(absBinaryPath); os.IsNotExist(err) {
			return fmt.Errorf("tool binary not found at '%s'", absBinaryPath)
		}

		// Execute tool binary directly
		toolCmd := exec.CommandContext(ctx, absBinaryPath)
		if toolInput != "" {
			toolCmd.Stdin = strings.NewReader(toolInput)
		}
		toolCmd.Stdout = os.Stdout
		toolCmd.Stderr = os.Stderr

		if err := toolCmd.Run(); err != nil {
			return fmt.Errorf("tool execution failed: %w", err)
		}

	case "info":
		if len(args) < 2 {
			return fmt.Errorf("usage: nerd tool info <name>")
		}
		toolName := args[1]

		fmt.Printf("🔧 Tool Info: %s\n", toolName)
		fmt.Println(strings.Repeat("─", 60))

		// Query tool details (filter results in Go since kernel.Query returns all facts)
		allDetails, _ := cortex.Kernel.Query("tool_description")
		for _, d := range allDetails {
			if len(d.Args) >= 2 && types.ExtractString(d.Args[0]) == toolName {
				fmt.Printf("Description: %v\n", d.Args[1])
				break
			}
		}

		allBinaries, _ := cortex.Kernel.Query("tool_binary_path")
		for _, b := range allBinaries {
			if len(b.Args) >= 2 && types.ExtractString(b.Args[0]) == toolName {
				fmt.Printf("Binary: %v\n", b.Args[1])
				break
			}
		}

	case "generate":
		if len(args) < 2 {
			return fmt.Errorf("usage: nerd tool generate <description>")
		}
		description := strings.Join(args[1:], " ")

		fmt.Printf("🔧 Generating Tool\n")
		fmt.Printf("📝 Description: %s\n", description)
		fmt.Println(strings.Repeat("─", 60))

		// Use Ouroboros via the autopoiesis orchestrator — the durable path
		// that writes, compiles, registers, and asserts tool_registered.
		// SpawnTask(tool_generator) previously returned planning prose
		// ("Generated self-tool X") with exit 0 while tool list stayed empty.
		if cortex.Orchestrator == nil {
			return fmt.Errorf("tool generation failed: autopoiesis orchestrator not initialized")
		}

		need, err := cortex.Orchestrator.DetectToolNeed(ctx, description)
		if err != nil {
			return fmt.Errorf("tool generation failed (detect): %w", err)
		}
		if need == nil {
			// Explicit CLI generate is authoritative — never no-op on weak detection.
			need = buildCLIToolNeed(description)
		}

		fmt.Printf("Detected need: %s\n", need.Name)
		fmt.Printf("Purpose: %s\n", need.Purpose)
		fmt.Println(strings.Repeat("─", 60))

		loopRes := cortex.Orchestrator.ExecuteOuroborosLoop(ctx, need)
		if loopRes == nil {
			return fmt.Errorf("tool generation failed: ouroboros returned nil result")
		}
		if !loopRes.Success {
			errMsg := loopRes.Error
			if errMsg == "" {
				errMsg = fmt.Sprintf("stopped at stage %v", loopRes.Stage)
			}
			return fmt.Errorf("tool generation failed: %s", errMsg)
		}
		if strings.TrimSpace(loopRes.ToolName) == "" {
			return fmt.Errorf("tool generation failed: empty tool name after claimed success")
		}

		// Verify durability: tool must appear in the registry ListTools sees.
		found := cortex.Orchestrator.HasGeneratedTool(loopRes.ToolName)
		if !found {
			for _, t := range cortex.Orchestrator.ListTools() {
				if t.Name == loopRes.ToolName {
					found = true
					break
				}
			}
		}
		if !found {
			return fmt.Errorf(
				"tool generation hollow success blocked: %q not visible to tool list after generate",
				loopRes.ToolName,
			)
		}

		fmt.Printf("✅ Tool registered: %s\n", loopRes.ToolName)
		if loopRes.CompileResult != nil && loopRes.CompileResult.OutputPath != "" {
			fmt.Printf("Binary: %s\n", loopRes.CompileResult.OutputPath)
		}
		fmt.Printf("Duration: %v\n", loopRes.Duration)
		fmt.Println("\nUse 'nerd tool list' to confirm, 'nerd tool run <name>' to execute.")

	default:
		return fmt.Errorf("unknown subcommand: %s (use list, run, info, or generate)", subCmd)
	}

	return nil
}

// buildCLIToolNeed constructs an authoritative ToolNeed for explicit
// `nerd tool generate` requests when DetectToolNeed returns nil.
func buildCLIToolNeed(description string) *autopoiesis.ToolNeed {
	return &autopoiesis.ToolNeed{
		Name:       toolNameFromDescription(description),
		Purpose:    strings.TrimSpace(description),
		Reasoning:  "cli_tool_generate",
		Confidence: 1.0,
		Priority:   1.0,
	}
}

var nonIdentRunes = regexp.MustCompile(`[^a-z0-9_]+`)

// toolNameFromDescription derives a stable snake_case tool name from free text.
func toolNameFromDescription(description string) string {
	s := strings.ToLower(strings.TrimSpace(description))
	if s == "" {
		return "generated_tool"
	}
	// Keep alphanumerics; collapse the rest to underscores.
	var b strings.Builder
	prevUnderscore := false
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			prevUnderscore = false
			continue
		}
		if !prevUnderscore {
			b.WriteByte('_')
			prevUnderscore = true
		}
	}
	name := strings.Trim(b.String(), "_")
	name = nonIdentRunes.ReplaceAllString(name, "_")
	name = strings.Trim(name, "_")
	if name == "" {
		return "generated_tool"
	}
	// Cap length so binary/path names stay manageable.
	if len(name) > 48 {
		name = name[:48]
		name = strings.Trim(name, "_")
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "tool_" + name
	}
	return name
}

// runJITStatus shows JIT compiler status
func runJITStatus(cmd *cobra.Command, args []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	fmt.Printf("⚡ JIT Prompt Compiler Status\n")
	fmt.Println(strings.Repeat("─", 60))

	// Resolve API key
	key := resolveAPIKey(apiKey, workspace)

	// Boot Cortex
	cortex, err := coresys.GetOrBootCortex(ctx, workspace, key, nil)
	if err != nil {
		return fmt.Errorf("failed to boot cortex: %w", err)
	}
	defer cortex.Close()

	// Get compiler stats
	if cortex.JITCompiler != nil {
		stats := cortex.JITCompiler.GetStats()
		fmt.Printf("Embedded Atoms:   %d\n", stats.EmbeddedAtomCount)
		fmt.Printf("Project Atoms:    %d\n", stats.ProjectAtomCount)
		fmt.Printf("Shard DBs:        %d\n", stats.ShardDBCount)
		fmt.Printf("Compilations:     %d\n", stats.TotalCompilations)
		fmt.Printf("Avg Time (ms):    %.2f\n", stats.AverageTimeMs)
	} else {
		fmt.Println("JIT Compiler not initialized")
	}

	// Show prompt atoms currently asserted in the kernel.
	//
	// This is NOT the corpus. prompt_atom facts are asserted per compile by the
	// selector (internal/prompt/selector.go, buildContextFacts + AssertBatch),
	// so on a freshly booted process — which `nerd jit` always is — the count is
	// necessarily zero. Printed bare next to "Embedded Atoms: 892" it read as
	// "the corpus failed to load", which is the opposite of the truth.
	//
	// The error was also being discarded, making a failed query indistinguishable
	// from an empty one. Same defect family as the glassbox and transparency
	// predicates fixed earlier: a diagnostic whose only possible answer here is
	// "nothing", phrased as a fact about the system.
	atoms, err := cortex.Kernel.Query("prompt_atom")
	switch {
	case err != nil:
		fmt.Printf("\nPrompt Atoms In Kernel: query failed (%v)\n", err)
	case len(atoms) == 0:
		fmt.Printf("\nPrompt Atoms In Kernel: 0 — none asserted yet.\n")
		fmt.Printf("  Atoms are asserted per compile, and this process has run %d.\n", statsCompilations(cortex))
		fmt.Printf("  The %d embedded atoms above are the corpus and are unaffected.\n", embeddedCount(cortex))
	default:
		fmt.Printf("\nPrompt Atoms In Kernel: %d\n", len(atoms))
		if len(atoms) <= 10 {
			for _, atom := range atoms {
				fmt.Printf("  - %v\n", atom.Args[0])
			}
		}
	}

	return nil
}

// statsCompilations and embeddedCount read the JIT stats defensively so the
// explanatory lines in `nerd jit` cannot themselves panic on a nil compiler.
func statsCompilations(cortex *coresys.Cortex) int {
	if cortex == nil || cortex.JITCompiler == nil {
		return 0
	}
	return int(cortex.JITCompiler.GetStats().TotalCompilations)
}

func embeddedCount(cortex *coresys.Cortex) int {
	if cortex == nil || cortex.JITCompiler == nil {
		return 0
	}
	return int(cortex.JITCompiler.GetStats().EmbeddedAtomCount)
}
