// Package init implements the "nerd init" cold-start initialization system.
package init

import (
	"codenerd/internal/atomicfile"
	"codenerd/internal/logging"
	"codenerd/internal/prompt"
	"codenerd/internal/session"
	"codenerd/internal/sqlpragmas"
	"codenerd/internal/store"
	"codenerd/internal/world"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "github.com/mattn/go-sqlite3" // SQLite driver
)

// buildProjectProfile constructs the project profile from analysis.
func (i *Initializer) buildProjectProfile() ProjectProfile {
	profile := ProjectProfile{
		ProjectID: generateProjectID(i.config.Workspace),
		Name:      filepath.Base(i.config.Workspace),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	// Researcher shard removed - using direct detection methods
	// Profile detection is now file-based only

	// Fallback: file-based language detection if kernel didn't provide it
	if profile.Language == "" || profile.Language == "unknown" {
		profile.Language = i.detectLanguageFromFiles()
	}

	// Detect dependencies for agent recommendations
	profile.Dependencies = i.detectDependencies()
	profile.Modules = i.detectModules()

	// Framework is derived from the dependency set, which is why it has to run
	// after detectDependencies.
	profile.Framework = detectFrameworkFromDependencies(profile.Dependencies)

	// Detect build system (B4 enhancement)
	buildSystemInfo := i.detectBuildSystemDetails()
	profile.BuildSystem = buildSystemInfo.Name
	profile.BuildSystemInfo = &buildSystemInfo

	// Detect project type (app vs library) (D2 enhancement)
	profile.ProjectType = i.detectProjectType()

	// Detect entry points (Smart /init detection)
	profile.EntryPoints = i.detectEntryPoints()

	// Set defaults for any missing values
	if profile.Language == "" {
		profile.Language = "unknown"
	}
	if profile.Architecture == "" {
		profile.Architecture = "unknown"
	}

	return profile
}

// saveProfile writes the project profile to disk.
func (i *Initializer) saveProfile(path string, profile ProjectProfile) error {
	data, err := json.MarshalIndent(profile, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

// generateFactsFile creates a Mangle facts file for the project.
func (i *Initializer) generateFactsFile(path string, profile ProjectProfile) (int, error) {
	var facts []string

	// Helper to escape strings for Mangle
	escapeString := func(s string) string {
		s = strings.ReplaceAll(s, `\`, `\\`)
		s = strings.ReplaceAll(s, `"`, `\"`)
		s = strings.ReplaceAll(s, "\n", " ")
		s = strings.ReplaceAll(s, "\r", "")
		return s
	}

	// Project identity facts - use escaped strings
	facts = append(facts, fmt.Sprintf(`project_profile("%s", "%s", "%s").`,
		escapeString(profile.ProjectID),
		escapeString(profile.Name),
		escapeString(profile.Description)))

	// Use sanitized name constants for language/framework/architecture
	if profile.Language != "" && profile.Language != "unknown" {
		facts = append(facts, fmt.Sprintf(`project_language(/%s).`, sanitizeForMangle(profile.Language)))
	}

	if profile.Framework != "" && profile.Framework != "unknown" {
		facts = append(facts, fmt.Sprintf(`project_framework(/%s).`, sanitizeForMangle(profile.Framework)))
	}

	if profile.Architecture != "" && profile.Architecture != "unknown" {
		facts = append(facts, fmt.Sprintf(`project_architecture(/%s).`, sanitizeForMangle(profile.Architecture)))
	}

	if profile.BuildSystem != "" {
		facts = append(facts, fmt.Sprintf(`build_system(/%s).`, sanitizeForMangle(profile.BuildSystem)))
	}

	// Pattern facts - sanitize each pattern
	for _, pattern := range profile.Patterns {
		facts = append(facts, fmt.Sprintf(`architectural_pattern(/%s).`, sanitizeForMangle(pattern)))
	}

	// Entry point facts - use escaped strings for paths
	for _, entry := range profile.EntryPoints {
		facts = append(facts, fmt.Sprintf(`entry_point("%s").`, escapeString(entry)))
	}

	// Project tool needs. Init measures which tools this project's shape
	// implies; the kernel decides whether and when to build them. See
	// generateProjectTools for why init does not generate them itself.
	facts = append(facts, projectToolNeedFacts(i.determineRequiredTools(profile))...)

	// Write facts file
	var content strings.Builder
	content.WriteString("# codeNERD Project Profile Facts\n")
	content.WriteString("# Generated by: nerd init\n")
	content.WriteString(fmt.Sprintf("# Timestamp: %s\n\n", time.Now().Format(time.RFC3339)))

	for _, fact := range facts {
		content.WriteString(fact + "\n")
	}

	if err := os.WriteFile(path, []byte(content.String()), 0644); err != nil {
		return 0, err
	}

	return len(facts), nil
}

// initPreferences initializes user preferences.
func (i *Initializer) initPreferences() UserPreferences {
	prefs := UserPreferences{
		Verbosity:        "concise",
		ExplanationLevel: "intermediate",
		RequireTests:     false,
		RequireReview:    false,
	}

	// Apply hints if provided
	for _, hint := range i.config.PreferenceHints {
		switch hint {
		case "table_driven_tests":
			prefs.TestStyle = "table_driven"
		case "conventional_commits":
			prefs.CommitStyle = "conventional"
		case "strict":
			prefs.RequireTests = true
			prefs.RequireReview = true
		case "beginner":
			prefs.ExplanationLevel = "beginner"
		case "expert":
			prefs.ExplanationLevel = "expert"
		}
	}

	return prefs
}

// hintOverriddenPreferenceKeys returns the preferences.json keys that this run's
// PreferenceHints set explicitly. An explicit hint is an instruction for this
// run and therefore outranks whatever is already on disk; every other key is
// merge-preserved.
func (i *Initializer) hintOverriddenPreferenceKeys() map[string]bool {
	keys := make(map[string]bool)
	for _, hint := range i.config.PreferenceHints {
		switch hint {
		case "table_driven_tests":
			keys["test_style"] = true
		case "conventional_commits":
			keys["commit_style"] = true
		case "strict":
			keys["require_tests"] = true
			keys["require_review"] = true
		case "beginner", "expert":
			keys["explanation_level"] = true
		}
	}
	return keys
}

// savePreferences merges the init-owned preference keys into
// .nerd/preferences.json and returns the values that ended up on disk.
//
// This used to be a bare MarshalIndent + WriteFile of a freshly defaulted
// UserPreferences, which truncated the whole document. `.nerd/preferences.json`
// is shared: internal/ux owns the v2.0 blocks (user_journey/onboarding,
// guidance, telemetry, metrics, learned_patterns) and SaveAgentPreferences owns
// agent_selection, which phase 6 of this very run may have just written. So
// `nerd init --force` — whose flag help promises "preserves learned
// preferences" — reset onboarding state, discarded the user's recorded intent
// corrections, dropped their agent accept/reject history, and reverted every
// autopoiesis-learned style key to its default.
//
// The file is now a merge target: keys already present win, missing keys are
// seeded with the computed default, keys this run was explicitly hinted about
// are overwritten, and unknown keys are carried through untouched. A corrupt
// file is a hard error rather than an excuse to clobber (same rule as
// SaveAgentPreferences).
func (i *Initializer) savePreferences(path string, prefs UserPreferences) (UserPreferences, error) {
	merged := make(map[string]any)

	existingData, readErr := os.ReadFile(path)
	if readErr != nil && !os.IsNotExist(readErr) {
		return prefs, fmt.Errorf("read existing preferences: %w", readErr)
	}
	if len(existingData) > 0 {
		if err := json.Unmarshal(existingData, &merged); err != nil {
			return prefs, fmt.Errorf("existing preferences.json is corrupt (refusing to overwrite): %w", err)
		}
	}

	defaultsJSON, err := json.Marshal(prefs)
	if err != nil {
		return prefs, err
	}
	defaults := make(map[string]any)
	if err := json.Unmarshal(defaultsJSON, &defaults); err != nil {
		return prefs, err
	}

	overrides := i.hintOverriddenPreferenceKeys()
	for key, value := range defaults {
		if _, present := merged[key]; present && !overrides[key] {
			continue
		}
		merged[key] = value
	}

	data, err := json.MarshalIndent(merged, "", "  ")
	if err != nil {
		return prefs, err
	}
	// Atomic, not truncating. This is a read-modify-write over a file shared
	// with internal/ux and SaveAgentPreferences, and the merge above treats a
	// corrupt existing file as a hard error — so a torn write here does not
	// just lose the merge, it wedges every later `nerd init` for this
	// workspace behind a file it refuses to parse.
	if err := atomicfile.WriteFile(path, data, 0644); err != nil {
		return prefs, err
	}

	// Report what is actually on disk, not what we would have written; the
	// summary and InitResult must not claim defaults the merge rejected.
	effective := prefs
	if err := json.Unmarshal(data, &effective); err != nil {
		return prefs, nil
	}
	return effective, nil
}

// populateProjectAtoms stores the project-specific prompt atoms in
// `.nerd/knowledge.db` and keeps them for corpus ingestion.
//
// Storing them in knowledge.db alone made them invisible to prompt assembly:
// the JIT compiler collects from `.nerd/prompts/corpus.db` and the per-agent
// `.nerd/shards/{agent}_knowledge.db`, never from the LocalStore. So the
// project's own language/framework/testing guidance was generated on every init
// and then never selected. Phase 5c ingests the same atoms into corpus.db.
func (i *Initializer) populateProjectAtoms(profile ProjectProfile) error {
	if i.localDB == nil {
		return fmt.Errorf("local database not initialized")
	}

	atomsToStore := i.buildProjectAtoms(profile)

	i.mu.Lock()
	i.projectAtoms = atomsToStore
	i.mu.Unlock()

	storedCount := 0
	for _, atom := range atomsToStore {
		if err := i.localDB.StorePromptAtom(atom); err != nil {
			// Log error but continue with other atoms
			fmt.Printf("   ⚠ Failed to store atom %s: %v\n", atom.AtomID, err)
		} else {
			storedCount++
		}
	}

	fmt.Printf("   ✓ Populated %d project-specific prompt atoms\n", storedCount)
	return nil
}

// buildProjectAtoms creates project-specific prompt atoms based on detected
// language, frameworks, and conventions. It performs no I/O so both the
// knowledge.db write and the corpus.db ingestion see exactly the same atoms.
func (i *Initializer) buildProjectAtoms(profile ProjectProfile) []*store.PromptAtom {
	var atomsToStore []*store.PromptAtom

	// Helper to create an atom
	createAtom := func(id, category, subcategory, content string, languages, frameworks []string, priority int) *store.PromptAtom {
		// Compute token count and hash
		tokenCount := estimateTokens(content)
		contentHash := computeContentHash(id, content)

		atom := &store.PromptAtom{
			AtomID:      id,
			Version:     1,
			Content:     content,
			TokenCount:  tokenCount,
			ContentHash: contentHash,
			Category:    category,
			Subcategory: subcategory,
			Languages:   languages,
			Frameworks:  frameworks,
			Priority:    priority,
			IsMandatory: false,
			CreatedAt:   time.Now(),
		}

		return atom
	}

	// ========================================================================
	// Language-Specific Atoms
	// ========================================================================

	lang := strings.ToLower(profile.Language)
	if lang != "" && lang != "unknown" {
		langConstant := "/" + sanitizeForMangle(lang)

		switch lang {
		case "go", "golang":
			// Go-specific guidance
			goAtom := createAtom(
				"project/go/conventions",
				"language",
				"conventions",
				`## Go Project Conventions

This project is written in Go. Follow these Go-specific best practices:

**Error Handling:**
- Always check and handle errors explicitly
- Use fmt.Errorf with %w verb for error wrapping
- Return errors rather than panicking in library code

**Naming:**
- Use camelCase for local variables
- Use PascalCase for exported functions/types
- Use short, descriptive names (prefer 'i' over 'index' in loops)

**Testing:**
- Write table-driven tests where appropriate
- Use t.Helper() in test helper functions
- Prefer t.Run for subtests

**Concurrency:**
- Use channels for communication between goroutines
- Prefer sync.WaitGroup or errgroup.Group for coordinating goroutines
- Always handle goroutine cleanup to prevent leaks`,
				[]string{langConstant},
				nil,
				70,
			)
			atomsToStore = append(atomsToStore, goAtom)

		case "python":
			pythonAtom := createAtom(
				"project/python/conventions",
				"language",
				"conventions",
				`## Python Project Conventions

This project is written in Python. Follow these Python-specific best practices:

**Code Style:**
- Follow PEP 8 style guidelines
- Use meaningful variable names (snake_case)
- Type hints for function signatures and class attributes

**Error Handling:**
- Use specific exception types
- Provide informative error messages
- Use context managers (with) for resource management

**Testing:**
- Use pytest for testing framework
- Write unit tests with descriptive names
- Use fixtures for test setup

**Dependencies:**
- Keep requirements.txt or pyproject.toml up to date
- Use virtual environments for isolation`,
				[]string{"/" + sanitizeForMangle("python")},
				nil,
				70,
			)
			atomsToStore = append(atomsToStore, pythonAtom)

		case "typescript", "javascript":
			tsAtom := createAtom(
				"project/typescript/conventions",
				"language",
				"conventions",
				`## TypeScript/JavaScript Project Conventions

This project uses TypeScript/JavaScript. Follow these best practices:

**Type Safety:**
- Use strict mode TypeScript settings
- Avoid 'any' type - use unknown or specific types
- Define interfaces for complex objects

**Code Style:**
- Use const/let instead of var
- Prefer arrow functions for callbacks
- Use async/await over raw Promises

**Error Handling:**
- Use try-catch for async operations
- Provide meaningful error messages
- Consider using Result types for error handling

**Testing:**
- Use Jest or Vitest for testing
- Write unit tests for business logic
- Mock external dependencies`,
				[]string{"/" + sanitizeForMangle(lang)},
				nil,
				70,
			)
			atomsToStore = append(atomsToStore, tsAtom)
		}
	}

	// ========================================================================
	// Framework-Specific Atoms
	// ========================================================================

	for _, framework := range profile.Dependencies {
		fwName := strings.ToLower(framework.Name)
		fwConstant := "/" + sanitizeForMangle(fwName)

		switch fwName {
		case "bubbletea", "github.com/charmbracelet/bubbletea":
			bubbleteaAtom := createAtom(
				"project/bubbletea/patterns",
				"framework",
				"tui",
				`## Bubbletea TUI Patterns

This project uses Bubbletea for terminal UI. Follow these patterns:

**Model-Update-View:**
- Implement tea.Model interface with Init, Update, View methods
- Keep state in the model struct
- Return Cmds from Update for async operations

**Message Handling:**
- Use type switches in Update to handle different message types
- Create custom message types for app-specific events
- Use tea.Batch to return multiple commands

**Commands:**
- Use tea.Tick for periodic updates
- Wrap I/O operations in commands
- Handle errors in messages

**Styling:**
- Use Lipgloss for consistent styling
- Define styles at package level
- Keep view rendering pure (no side effects)`,
				nil,
				[]string{fwConstant},
				75,
			)
			atomsToStore = append(atomsToStore, bubbleteaAtom)

		case "gin", "gin-gonic", "github.com/gin-gonic/gin":
			ginAtom := createAtom(
				"project/gin/patterns",
				"framework",
				"webapi",
				`## Gin Web Framework Patterns

This project uses Gin for HTTP APIs. Follow these patterns:

**Router Setup:**
- Group related routes using router.Group()
- Use middleware for cross-cutting concerns (auth, logging, CORS)
- Define clear route hierarchies

**Handler Functions:**
- Use c.BindJSON() for request body parsing
- Return consistent error responses
- Use c.JSON() for response marshaling
- Set appropriate HTTP status codes

**Error Handling:**
- Create custom error types for domain errors
- Use middleware for centralized error handling
- Log errors with sufficient context

**Testing:**
- Use httptest for testing handlers
- Test middleware separately
- Verify status codes and response bodies`,
				nil,
				[]string{fwConstant},
				75,
			)
			atomsToStore = append(atomsToStore, ginAtom)

		case "react":
			reactAtom := createAtom(
				"project/react/patterns",
				"framework",
				"frontend",
				`## React Framework Patterns

This project uses React for frontend development. Follow these patterns:

**Component Structure:**
- Prefer functional components with hooks
- Keep components small and focused
- Extract custom hooks for reusable logic

**State Management:**
- Use useState for local state
- Use useEffect for side effects
- Consider useReducer for complex state
- Use Context API for shared state

**Performance:**
- Use React.memo for expensive components
- Use useMemo and useCallback appropriately
- Avoid unnecessary re-renders

**Error Handling:**
- Use Error Boundaries for component errors
- Handle async errors in effects
- Provide user-friendly error messages`,
				nil,
				[]string{"/" + sanitizeForMangle("react")},
				75,
			)
			atomsToStore = append(atomsToStore, reactAtom)
		}
	}

	// ========================================================================
	// Project Convention Atoms (inferred from project structure)
	// ========================================================================

	// Check if project follows specific patterns
	if len(profile.TestDirectories) > 0 {
		testingAtom := createAtom(
			"project/testing/conventions",
			"methodology",
			"testing",
			fmt.Sprintf(`## Project Testing Conventions

This project has organized test directories: %s

**Testing Standards:**
- Write tests for all new functionality
- Maintain existing test coverage
- Run tests before committing changes
- Keep test files alongside source files

**Test Organization:**
- Use clear test function names that describe what is being tested
- Group related tests together
- Use test fixtures for common setup

**Coverage:**
- Aim for meaningful coverage of business logic
- Don't test trivial getters/setters
- Focus on edge cases and error paths`,
				strings.Join(profile.TestDirectories, ", ")),
			nil,
			nil,
			60,
		)
		atomsToStore = append(atomsToStore, testingAtom)
	}

	// Build system specific guidance
	if profile.BuildSystem != "" && profile.BuildSystem != "unknown" {
		buildAtom := createAtom(
			"project/build/system",
			"domain",
			"build",
			fmt.Sprintf(`## Build System

This project uses %s for building.

**Build Commands:**
- Follow existing build scripts and configurations
- Update build config when adding dependencies
- Verify builds pass before committing

**Dependencies:**
- Keep dependency declarations up to date
- Document any special build requirements
- Use version pinning for stability`,
				profile.BuildSystem),
			nil,
			nil,
			50,
		)
		atomsToStore = append(atomsToStore, buildAtom)
	}

	// Architecture pattern guidance
	if len(profile.Patterns) > 0 {
		var patternsContent strings.Builder
		patternsContent.WriteString("## Architectural Patterns\n\nThis project follows these patterns:\n\n")
		for _, pattern := range profile.Patterns {
			patternsContent.WriteString(fmt.Sprintf("- **%s**: Follow this pattern consistently across the codebase\n", pattern))
		}

		archAtom := createAtom(
			"project/architecture/patterns",
			"domain",
			"architecture",
			patternsContent.String(),
			nil,
			nil,
			65,
		)
		atomsToStore = append(atomsToStore, archAtom)
	}

	return atomsToStore
}

// estimateTokens estimates token count for content (chars/4 approximation)
func estimateTokens(content string) int {
	if content == "" {
		return 0
	}
	return (len(content) + 3) / 4
}

// computeContentHash computes a content hash for deduplication.
//
// This was `fmt.Sprintf("%x", len(id+":"+content))` — a length, not a hash. Two
// different atoms of equal length collided, and editing an atom without
// changing its length produced an identical "hash". Now that these atoms are
// ingested into the JIT corpus, content_hash drives cache invalidation there,
// so a collision would serve stale prompt content.
func computeContentHash(id, content string) string {
	sum := sha256.Sum256([]byte(id + ":" + content))
	return hex.EncodeToString(sum[:])
}

// projectAtomToPromptAtom converts a LocalStore prompt atom into the JIT
// compiler's atom type. source_file is deliberately left unset by the loader:
// ReconcilePromptCorpus only deletes rows that claim an owner, so a NULL
// source_file is what marks these as project-owned and keeps them from being
// swept away when the embedded corpus is reconciled.
func projectAtomToPromptAtom(atom *store.PromptAtom) *prompt.PromptAtom {
	return &prompt.PromptAtom{
		ID:          atom.AtomID,
		Version:     atom.Version,
		Content:     atom.Content,
		TokenCount:  atom.TokenCount,
		ContentHash: atom.ContentHash,
		Category:    prompt.AtomCategory(atom.Category),
		Subcategory: atom.Subcategory,
		Languages:   atom.Languages,
		Frameworks:  atom.Frameworks,
		Priority:    atom.Priority,
		IsMandatory: atom.IsMandatory,
	}
}

// ingestProjectAtomsIntoCorpus writes the atoms built in phase 5b into the JIT
// prompt corpus so prompt assembly can actually select them. It runs after
// ReconcilePromptCorpus so the reconciliation pass can never observe (and
// therefore never delete) a partially written project atom.
func (i *Initializer) ingestProjectAtomsIntoCorpus(ctx context.Context, db *sql.DB) (int, error) {
	i.mu.RLock()
	atoms := i.projectAtoms
	i.mu.RUnlock()

	if len(atoms) == 0 {
		return 0, nil
	}

	loader := prompt.NewAtomLoader(i.embedEngine)
	ingested := 0
	for _, atom := range atoms {
		if atom == nil {
			continue
		}
		if err := loader.StoreAtom(ctx, db, projectAtomToPromptAtom(atom)); err != nil {
			return ingested, fmt.Errorf("ingest project atom %s: %w", atom.AtomID, err)
		}
		ingested++
	}
	return ingested, nil
}

// initSessionState creates the initial session state file.
func (i *Initializer) initSessionState(path string) error {
	state := session.SessionState{
		SessionID:    generateSessionID(),
		StartedAt:    time.Now(),
		LastActiveAt: time.Now(),
		TurnCount:    0,
		Suspended:    false,
	}

	workspace := i.config.Workspace
	if workspace == "" {
		workspace = filepath.Dir(filepath.Dir(path))
	}
	return session.SaveSessionState(workspace, &state)
}

// LoadProjectProfile loads the project profile from .nerd/profile.json
func LoadProjectProfile(workspace string) (*ProjectProfile, error) {
	path := filepath.Join(workspace, ".nerd", "profile.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var profile ProjectProfile
	if err := json.Unmarshal(data, &profile); err != nil {
		return nil, err
	}

	return &profile, nil
}

// LoadPreferences loads user preferences from .nerd/preferences.json
func LoadPreferences(workspace string) (*UserPreferences, error) {
	path := filepath.Join(workspace, ".nerd", "preferences.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var prefs UserPreferences
	if err := json.Unmarshal(data, &prefs); err != nil {
		return nil, err
	}

	return &prefs, nil
}


// ListSessionHistories returns all available session histories.
func ListSessionHistories(workspace string) ([]string, error) {
	sessionsDir := filepath.Join(workspace, ".nerd", "sessions")
	entries, err := os.ReadDir(sessionsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, err
	}

	var sessions []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".json") {
			sessions = append(sessions, strings.TrimSuffix(entry.Name(), ".json"))
		}
	}
	return sessions, nil
}

// GetLatestSession returns the most recent session ID.
func GetLatestSession(workspace string) (string, error) {
	state, err := session.LoadSessionState(workspace)
	if err != nil {
		return "", err
	}
	return state.SessionID, nil
}

// IsInitialized checks if the workspace has been initialized.
func IsInitialized(workspace string) bool {
	nerdDir := filepath.Join(workspace, ".nerd")
	profilePath := filepath.Join(nerdDir, "profile.json")

	if _, err := os.Stat(profilePath); err == nil {
		return true
	}
	return false
}

// createCodebaseKnowledgeBase creates a knowledge base with project-specific facts.
func (i *Initializer) createCodebaseKnowledgeBase(_ context.Context, nerdDir string, profile ProjectProfile, scanResult *world.ScanResult) (string, int, error) {
	kbPath := filepath.Join(nerdDir, "shards", "codebase_knowledge.db")

	// Create the knowledge store
	codebaseDB, err := store.NewLocalStore(kbPath)
	if err != nil {
		return "", 0, fmt.Errorf("failed to create codebase KB: %w", err)
	}
	if err := i.ensureEmbeddingEngine(); err != nil {
		return "", 0, err
	}
	codebaseDB.SetEmbeddingEngine(i.embedEngine)
	defer codebaseDB.Close()

	atomCount := 0

	// Store project identity
	if err := codebaseDB.StoreKnowledgeAtom("project_identity", fmt.Sprintf(
		"This is %s, a %s project. %s",
		profile.Name, profile.Language, profile.Description), 1.0); err == nil {
		atomCount++
	}

	// Store language and framework
	if profile.Language != "" && profile.Language != "unknown" {
		if err := codebaseDB.StoreKnowledgeAtom("primary_language", profile.Language, 1.0); err == nil {
			atomCount++
		}
	}
	if profile.Framework != "" && profile.Framework != "unknown" {
		if err := codebaseDB.StoreKnowledgeAtom("framework", profile.Framework, 0.95); err == nil {
			atomCount++
		}
	}

	// Store file topology summary
	if scanResult != nil {
		summary := fmt.Sprintf("Project contains %d files in %d directories (%d test files).",
			scanResult.FileCount, scanResult.DirectoryCount, scanResult.TestFileCount)
		if err := codebaseDB.StoreKnowledgeAtom("file_topology_summary", summary, 0.9); err == nil {
			atomCount++
		}

		// Store language breakdown
		for lang, count := range scanResult.Languages {
			content := fmt.Sprintf("Language %s: %d files", lang, count)
			if err := codebaseDB.StoreKnowledgeAtom("language_stats", content, 0.85); err == nil {
				atomCount++
			}
		}
	}

	// Store entry points
	for _, entry := range profile.EntryPoints {
		if err := codebaseDB.StoreKnowledgeAtom("entry_point", entry, 0.95); err == nil {
			atomCount++
		}
	}

	// Store dependencies
	for _, dep := range profile.Dependencies {
		content := fmt.Sprintf("Dependency: %s (%s)", dep.Name, dep.Type)
		if err := codebaseDB.StoreKnowledgeAtom("dependency", content, 0.9); err == nil {
			atomCount++
		}
	}

	// Store architectural patterns
	for _, pattern := range profile.Patterns {
		if err := codebaseDB.StoreKnowledgeAtom("architectural_pattern", pattern, 0.85); err == nil {
			atomCount++
		}
	}

	return kbPath, atomCount, nil
}

// createCampaignKnowledgeBase creates a knowledge base for campaign orchestration.
func (i *Initializer) createCampaignKnowledgeBase(_ context.Context, nerdDir string, profile ProjectProfile) (string, int, error) {
	kbPath := filepath.Join(nerdDir, "shards", "campaign_knowledge.db")

	campaignDB, err := store.NewLocalStore(kbPath)
	if err != nil {
		return "", 0, fmt.Errorf("failed to create campaign KB: %w", err)
	}
	if err := i.ensureEmbeddingEngine(); err != nil {
		return "", 0, err
	}
	campaignDB.SetEmbeddingEngine(i.embedEngine)
	defer campaignDB.Close()

	atomCount := 0

	// Campaign orchestration concepts
	concepts := []struct{ Key, Value string }{
		{"campaign_identity", "I am the Campaign orchestrator. I manage multi-phase development tasks."},
		{"capability_planning", "I can break complex tasks into phases with dependencies."},
		{"capability_delegation", "I can delegate tasks to specialized shards (Coder, Reviewer, Tester)."},
		{"capability_checkpoints", "I validate phase completion before proceeding."},
		{"capability_replanning", "I can replan when tasks fail or requirements change."},
		{"phase_types", "Common phases: research, design, implement, test, review, integrate."},
		{"safety_rule", "Failed checkpoints block phase advancement."},
		{"safety_rule", "Critical security findings block campaign completion."},
		{"learning_rule", "Successful patterns are promoted to long-term memory."},
		{"learning_rule", "Repeated failures trigger strategy adjustment."},
	}

	for _, concept := range concepts {
		if err := campaignDB.StoreKnowledgeAtom(concept.Key, concept.Value, 0.95); err == nil {
			atomCount++
		}
	}

	// Store project-specific campaign context
	if err := campaignDB.StoreKnowledgeAtom("project_context",
		fmt.Sprintf("Campaigns for %s (%s project)", profile.Name, profile.Language), 0.9); err == nil {
		atomCount++
	}

	// Store build system info for execution
	if profile.BuildSystem != "" {
		if err := campaignDB.StoreKnowledgeAtom("build_system", profile.BuildSystem, 0.9); err == nil {
			atomCount++
		}
	}

	// Research campaign patterns - STUBBED (JIT refactor)
	// Research is now handled on-demand via session.Executor with /researcher persona
	if i.config.LLMClient != nil && !i.config.SkipResearch {
		logging.Boot("Campaign research stubbed (JIT refactor) - using base atoms only")
	}

	return kbPath, atomCount, nil
}

// Helper functions

func generateProjectID(workspace string) string {
	// Simple hash-based ID
	h := uint64(0)
	for _, c := range workspace {
		h = h*31 + uint64(c)
	}
	return fmt.Sprintf("proj_%x", h)[:16]
}

func generateSessionID() string {
	return fmt.Sprintf("sess_%d", time.Now().UnixNano())
}

func cleanNameConstant(s string) string {
	// Remove leading "/" from Mangle name constants
	if len(s) > 0 && s[0] == '/' {
		return s[1:]
	}
	return s
}

// sanitizeForMangle converts a string to a valid Mangle name constant.
// Mangle name constants must be lowercase alphanumeric with underscores.
func sanitizeForMangle(s string) string {
	if s == "" {
		return "unknown"
	}

	// Convert to lowercase
	s = strings.ToLower(s)

	// Replace spaces and special characters with underscores
	var result strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			result.WriteRune(c)
		} else if c == ' ' || c == '-' || c == '.' || c == '/' {
			result.WriteRune('_')
		}
		// Skip other characters
	}

	// Ensure it doesn't start with a number
	sanitized := result.String()
	if len(sanitized) > 0 && sanitized[0] >= '0' && sanitized[0] <= '9' {
		sanitized = "n" + sanitized
	}

	// Remove consecutive underscores and trim
	for strings.Contains(sanitized, "__") {
		sanitized = strings.ReplaceAll(sanitized, "__", "_")
	}
	sanitized = strings.Trim(sanitized, "_")

	if sanitized == "" {
		return "unknown"
	}

	return sanitized
}

// initializePromptDatabase ensures the .nerd/prompts/corpus.db exists and has the
// prompt atom schema required by the JIT prompt compiler.
func (i *Initializer) initializePromptDatabase(ctx context.Context, nerdDir string) error {
	logging.Boot("Initializing prompt corpus database...")

	// Path to the corpus database
	dbPath := filepath.Join(nerdDir, "prompts", "corpus.db")

	// Ensure directory exists
	dir := filepath.Dir(dbPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Seed from baked defaults if available (never overwrites an existing DB).
	if _, err := prompt.MaterializeDefaultPromptCorpus(dbPath); err != nil {
		return fmt.Errorf("failed to materialize default prompt corpus: %w", err)
	}

	// Open database
	db, err := sql.Open("sqlite3", dbPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()
	sqlpragmas.ApplyDefaultPragmas(db, sqlpragmas.ProfileBulkBuild)

	atomLoader := prompt.NewAtomLoader(nil)
	if err := atomLoader.EnsureSchema(ctx, db); err != nil {
		return fmt.Errorf("failed to ensure corpus schema: %w", err)
	}

	// Best-effort: restore the canonical embedded atom set while preserving
	// project-owned rows. Runtime collection still gives embedded atoms
	// precedence if reconciliation cannot complete.
	if embedded, err := prompt.LoadEmbeddedCorpus(); err == nil {
		if counts, err := prompt.ReconcilePromptCorpus(ctx, db, embedded.All()); err != nil {
			logging.Boot("Warning: failed to reconcile prompt corpus: %v", err)
		} else {
			logging.Boot("Reconciled prompt corpus: upserted=%d deleted=%d retained_embeddings=%d cleared_embeddings=%d", counts.Upserted, counts.Deleted, counts.RetainedEmbeddings, counts.ClearedEmbeddings)
		}
	}

	// Project atoms land after reconciliation so the sweep cannot race them.
	if ingested, err := i.ingestProjectAtomsIntoCorpus(ctx, db); err != nil {
		return fmt.Errorf("failed to ingest project prompt atoms: %w", err)
	} else if ingested > 0 {
		logging.Boot("Ingested %d project prompt atoms into corpus.db", ingested)
		fmt.Printf("   ✓ Ingested %d project-specific atoms into the JIT corpus\n", ingested)
	}

	logging.Boot("Prompt corpus database initialized successfully")
	fmt.Println("   ✓ Prompt corpus database ready")
	return nil
}
