package world

import (
	"reflect"
	"testing"
)

func TestDetectCodePatterns(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		elements []CodeElement
		want     CodePatterns
	}{
		{
			name:    "empty content",
			content: "",
			want:    CodePatterns{},
		},
		{
			name:    "generated code - protobuf",
			content: "// Code generated by protoc-gen-go\npackage main\n",
			want: CodePatterns{
				IsGenerated:     true,
				Generator:       "protobuf",
				GeneratorMarker: "Code generated by protoc-gen-go",
			},
		},
		{
			name:    "generated code - sqlc",
			content: "// Code generated by sqlc\npackage main\n",
			want: CodePatterns{
				IsGenerated:     true,
				Generator:       "sqlc",
				GeneratorMarker: "Code generated by sqlc",
			},
		},
		{
			name:    "cgo - import C",
			content: "package main\n\nimport \"C\"\n",
			want: CodePatterns{
				HasCGo: true,
			},
		},
		{
			name:    "cgo - include",
			content: "package main\n\n/*\n#include <stdlib.h>\n*/\nimport \"C\"\n",
			want: CodePatterns{
				HasCGo: true,
			},
		},
		{
			name:    "build tags",
			content: "//go:build linux\n// +build linux\n\npackage main\n",
			want: CodePatterns{
				BuildTags: []string{"linux", "linux"},
			},
		},
		{
			name:    "embed directive",
			content: "package main\n\nimport \"embed\"\n\n//go:embed static/*\nvar content embed.FS\n",
			want: CodePatterns{
				EmbedDirectives: []string{"static/*"},
			},
		},
		{
			name:    "api client - GET",
			content: "",
			elements: []CodeElement{
				{
					Ref:  "fn:main",
					Type: ElementFunction,
					Body: "res, err := http.Get(\"http://example.com\")\n",
				},
			},
			want: CodePatterns{
				APIClientFuncs: []APIPattern{
					{Ref: "fn:main", Method: "GET"},
				},
			},
		},
		{
			name:    "api client - POST",
			content: "",
			elements: []CodeElement{
				{
					Ref:  "fn:DoPost",
					Type: ElementFunction,
					Body: "res, err := http.Post(\"http://example.com\", \"application/json\", nil)\n",
				},
			},
			want: CodePatterns{
				APIClientFuncs: []APIPattern{
					{Ref: "fn:DoPost", Method: "POST"},
				},
			},
		},
		{
			name:    "api handler - standard lib",
			content: "",
			elements: []CodeElement{
				{
					Ref:  "fn:setupRoutes",
					Type: ElementFunction,
					Body: "http.HandleFunc(\"/\", handler)\n",
				},
			},
			want: CodePatterns{
				APIHandlerFuncs: []APIPattern{
					{Ref: "fn:setupRoutes", Method: "ANY"},
				},
			},
		},
		{
			name:    "api handler - gin",
			content: "",
			elements: []CodeElement{
				{
					Ref:  "fn:ginHandler",
					Type: ElementFunction,
					Body: "func(c *gin.Context) {\n  c.JSON(200, gin.H{\"message\": \"ok\"})\n}\n",
				},
			},
			want: CodePatterns{
				APIHandlerFuncs: []APIPattern{
					{Ref: "fn:ginHandler", Method: "ANY"},
				},
			},
		},
		{
			name:    "multiple patterns",
			content: "//go:build linux\n// Code generated by swagger\npackage main\n\nimport \"C\"\n",
			elements: []CodeElement{
				{
					Ref:  "fn:fetchData",
					Type: ElementFunction,
					Body: "http.Get(\"http://api.com\")\n",
				},
				{
					Ref:  "fn:serve",
					Type: ElementFunction,
					Body: "router.GET(\"/api\", handler)\n",
				},
			},
			want: CodePatterns{
				IsGenerated:     true,
				Generator:       "swagger",
				GeneratorMarker: "Code generated by swagger",
				HasCGo:          true,
				BuildTags:       []string{"linux"},
				APIClientFuncs: []APIPattern{
					{Ref: "fn:fetchData", Method: "GET"},
				},
				APIHandlerFuncs: []APIPattern{
					{Ref: "fn:serve", Method: "ANY"},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := DetectCodePatterns(tt.content, tt.elements)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("DetectCodePatterns() = %+v, want %+v", got, tt.want)
			}
		})
	}
}
