package world

import (
	"codenerd/internal/core"
	"errors"
	"reflect"
	"sort"
	"testing"
)

// mockCodeParser implements CodeParser for testing ParserFactory.
type mockCodeParser struct {
	language      string
	extensions    []string
	parseFunc     func(path string, content []byte) ([]CodeElement, error)
	emitFactsFunc func(elements []CodeElement) []core.Fact
}

func (m *mockCodeParser) Parse(path string, content []byte) ([]CodeElement, error) {
	if m.parseFunc != nil {
		return m.parseFunc(path, content)
	}
	return nil, nil
}

func (m *mockCodeParser) SupportedExtensions() []string {
	return m.extensions
}

func (m *mockCodeParser) EmitLanguageFacts(elements []CodeElement) []core.Fact {
	if m.emitFactsFunc != nil {
		return m.emitFactsFunc(elements)
	}
	return nil
}

func (m *mockCodeParser) Language() string {
	return m.language
}

func TestParserFactory_ParseWithFacts(t *testing.T) {
	factory := NewParserFactory("/project")

	// 1. Error when extension is unregistered
	_, err := factory.ParseWithFacts("test.unknown", []byte("content"))
	if err == nil || err.Error() != "no parser registered for extension: .unknown" {
		t.Errorf("Expected unregistered extension error, got %v", err)
	}

	// 2. Error when underlying parser fails
	expectedErr := errors.New("parse error")
	mockParserErr := &mockCodeParser{
		language:   "mock",
		extensions: []string{".mock"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			return nil, expectedErr
		},
	}
	factory.Register(mockParserErr)
	_, err = factory.ParseWithFacts("test.mock", []byte("content"))
	if err != expectedErr {
		t.Errorf("Expected underlying parser error, got %v", err)
	}

	// 3. Successful parsing
	mockElements := []CodeElement{
		{Type: "/struct", Name: "User"},
	}
	mockFacts := []core.Fact{
		{Predicate: "mock_struct"},
	}
	mockParserSuccess := &mockCodeParser{
		language:   "mock2",
		extensions: []string{".mock2"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			return mockElements, nil
		},
		emitFactsFunc: func(elements []CodeElement) []core.Fact {
			return mockFacts
		},
	}
	factory.Register(mockParserSuccess)

	// Include a pattern marker to test pattern detection
	content := []byte("// Code generated by protoc-gen-go")
	res, err := factory.ParseWithFacts("test.mock2", content)
	if err != nil {
		t.Fatalf("Expected successful parse, got %v", err)
	}

	if len(res.Elements) != 1 || res.Elements[0].Name != "User" {
		t.Errorf("Unexpected elements returned")
	}
	if len(res.LanguageFacts) != 1 || res.LanguageFacts[0].Predicate != "mock_struct" {
		t.Errorf("Unexpected language facts returned")
	}
	if !res.Patterns.IsGenerated || res.Patterns.Generator != "protobuf" {
		t.Errorf("Expected protobuf pattern detection, got generated=%v generator=%s", res.Patterns.IsGenerated, res.Patterns.Generator)
	}
}

func TestParserFactory_EmitAllFacts(t *testing.T) {
	factory := NewParserFactory("/project")

	elements := []CodeElement{
		{Ref: "mock:test.mock2:User", Type: "/struct", Name: "User"},
	}

	langFacts := []core.Fact{
		{Predicate: "mock_lang_fact"},
	}

	patterns := CodePatterns{
		IsGenerated: true,
		Generator:   "mock_generator",
	}

	res := &ParseResult{
		Elements:      elements,
		LanguageFacts: langFacts,
		Patterns:      patterns,
	}

	allFacts := factory.EmitAllFacts(res, "test.mock2")

	// Expect facts from:
	// 1. CodeElement.ToFacts() -> code_element fact
	// 2. Language facts -> mock_lang_fact
	// 3. Pattern facts -> pattern_generated (Wait, let's see ToPatternFacts)
	// If IsGenerated = true, Predicate is "generated_code"

	foundElem := false
	foundLang := false
	foundPattern := false

	for _, f := range allFacts {
		if f.Predicate == "code_element" {
			foundElem = true
		} else if f.Predicate == "mock_lang_fact" {
			foundLang = true
		} else if f.Predicate == "generated_code" {
			foundPattern = true
		}
	}

	if !foundElem { t.Error("Missing code_element facts") }
	if !foundLang { t.Error("Missing language facts") }
	if !foundPattern { t.Error("Missing pattern facts") }
}

func TestParserFactory_RegisteredLanguages(t *testing.T) {
	factory := NewParserFactory("/project")

	factory.Register(&mockCodeParser{
		language:   "lang1",
		extensions: []string{".l1", ".l1x"},
	})
	factory.Register(&mockCodeParser{
		language:   "lang2",
		extensions: []string{".l2"},
	})

	langs := factory.RegisteredLanguages()
	sort.Strings(langs)
	expected := []string{"lang1", "lang2"}

	if !reflect.DeepEqual(langs, expected) {
		t.Errorf("Expected registered languages %v, got %v", expected, langs)
	}
}

func TestParserFactory_Paths(t *testing.T) {
	factory := NewParserFactory("/my/project/root")

	if root := factory.ProjectRoot(); root != "/my/project/root" {
		t.Errorf("Expected project root /my/project/root, got %s", root)
	}

	// Should compute relative path
	rel := factory.RelativePath("/my/project/root/src/file.go")
	if rel != "src/file.go" {
		t.Errorf("Expected relative path src/file.go, got %s", rel)
	}

	// If outside root, should return absolute path (or path relative with ..)
	// Rel returns an error if base and target are completely disconnected, but they share '/' here.
	// But let's test a simple relative check that doesn't fail filepath.Rel
	relOuter := factory.RelativePath("/other/path")
	if relOuter == "" {
		t.Errorf("Expected non-empty path for outside project root")
	}
}

func TestParserFactory_SupportedExtensions(t *testing.T) {
	factory := NewParserFactory("/project")

	factory.Register(&mockCodeParser{
		language:   "lang1",
		extensions: []string{".a", ".B"},
	})

	exts := factory.SupportedExtensions()
	sort.Strings(exts)
	expected := []string{".a", ".b"} // The factory normalizes extensions to lowercase.

	if !reflect.DeepEqual(exts, expected) {
		t.Errorf("Expected supported extensions %v, got %v", expected, exts)
	}
}
