package world

import (
	"codenerd/internal/core"
	"errors"
	"path/filepath"
	"sort"
	"testing"
)

// mockParser is a test double for the CodeParser interface.
type mockParser struct {
	language      string
	extensions    []string
	parseFunc     func(path string, content []byte) ([]CodeElement, error)
	emitFactsFunc func(elements []CodeElement) []core.Fact
}

func (m *mockParser) Parse(path string, content []byte) ([]CodeElement, error) {
	if m.parseFunc != nil {
		return m.parseFunc(path, content)
	}
	return []CodeElement{{Ref: path}}, nil
}

func (m *mockParser) SupportedExtensions() []string {
	return m.extensions
}

func (m *mockParser) EmitLanguageFacts(elements []CodeElement) []core.Fact {
	if m.emitFactsFunc != nil {
		return m.emitFactsFunc(elements)
	}
	return []core.Fact{}
}

func (m *mockParser) Language() string {
	return m.language
}

func TestNewParserFactory(t *testing.T) {
	factory := NewParserFactory("/project/root")
	if factory.ProjectRoot() != "/project/root" {
		t.Errorf("Expected project root '/project/root', got '%s'", factory.ProjectRoot())
	}
	if len(factory.SupportedExtensions()) != 0 {
		t.Errorf("Expected 0 parsers, got %d", len(factory.SupportedExtensions()))
	}
}

func TestParserFactory_Register(t *testing.T) {
	factory := NewParserFactory("/")

	p1 := &mockParser{language: "test1", extensions: []string{".t1", "t2", ".T3"}}
	factory.Register(p1)

	if !factory.HasParser("file.t1") {
		t.Errorf("Failed to register extension .t1")
	}
	if !factory.HasParser("file.t2") { // Should have dot added
		t.Errorf("Failed to register extension t2")
	}
	if !factory.HasParser("file.t3") { // Should be lowercased
		t.Errorf("Failed to register extension .T3")
	}

	p2 := &mockParser{language: "test2", extensions: []string{".t1"}} // override
	factory.Register(p2)

	parser := factory.GetParser("file.t1")
	if parser.Language() != "test2" {
		t.Errorf("Expected parser to be overridden by test2, got %s", parser.Language())
	}
}

func TestParserFactory_GetParser_HasParser(t *testing.T) {
	factory := NewParserFactory("/")
	p := &mockParser{language: "test", extensions: []string{".test"}}
	factory.Register(p)

	if factory.GetParser("file.test") == nil {
		t.Errorf("Expected parser for .test")
	}
	if factory.GetParser("file.unknown") != nil {
		t.Errorf("Expected nil parser for .unknown")
	}

	if !factory.HasParser("file.test") {
		t.Errorf("Expected HasParser to be true for .test")
	}
	if factory.HasParser("file.unknown") {
		t.Errorf("Expected HasParser to be false for .unknown")
	}
}

func TestParserFactory_Parse(t *testing.T) {
	factory := NewParserFactory("/")

	expectedErr := errors.New("parse error")
	p := &mockParser{
		language: "test",
		extensions: []string{".test"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			if string(content) == "error" {
				return nil, expectedErr
			}
			return []CodeElement{{Ref: "test:ref"}}, nil
		},
	}
	factory.Register(p)

	// Test successful parse
	elems, err := factory.Parse("file.test", []byte("content"))
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	if len(elems) != 1 || elems[0].Ref != "test:ref" {
		t.Errorf("Unexpected elements returned")
	}

	// Test parse error
	_, err = factory.Parse("file.test", []byte("error"))
	if err != expectedErr {
		t.Errorf("Expected parse error, got %v", err)
	}

	// Test no parser
	_, err = factory.Parse("file.unknown", []byte("content"))
	if err == nil {
		t.Errorf("Expected error for missing parser")
	}
}

func TestParserFactory_ParseWithFacts(t *testing.T) {
	factory := NewParserFactory("/")

	p := &mockParser{
		language: "test",
		extensions: []string{".test"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			return []CodeElement{{Ref: "test:ref"}}, nil
		},
		emitFactsFunc: func(elements []CodeElement) []core.Fact {
			return []core.Fact{{Predicate: "test_fact"}}
		},
	}
	factory.Register(p)

	res, err := factory.ParseWithFacts("file.test", []byte("Code generated by protoc"))
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(res.Elements) != 1 {
		t.Errorf("Expected 1 element")
	}
	if len(res.LanguageFacts) != 1 || res.LanguageFacts[0].Predicate != "test_fact" {
		t.Errorf("Expected language facts to be populated")
	}
	if !res.Patterns.IsGenerated || res.Patterns.Generator != "protobuf" {
		t.Errorf("Expected patterns to detect protobuf generated code")
	}

	// Test missing parser
	_, err = factory.ParseWithFacts("file.unknown", nil)
	if err == nil {
		t.Errorf("Expected error for missing parser")
	}

	// Test parser error
	p.parseFunc = func(path string, content []byte) ([]CodeElement, error) {
		return nil, errors.New("parse error")
	}
	_, err = factory.ParseWithFacts("file.test", nil)
	if err == nil || err.Error() != "parse error" {
		t.Errorf("Expected parse error to propagate")
	}
}

func TestParserFactory_EmitAllFacts(t *testing.T) {
	factory := NewParserFactory("/")

	p := &mockParser{
		language: "test",
		extensions: []string{".test"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			return []CodeElement{{Ref: "test:ref", Type: "/function"}}, nil
		},
		emitFactsFunc: func(elements []CodeElement) []core.Fact {
			return []core.Fact{{Predicate: "lang_fact"}}
		},
	}
	factory.Register(p)

	res, err := factory.ParseWithFacts("file.test", []byte("Code generated by protoc"))
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	facts := factory.EmitAllFacts(res, "file.test")

	// Expect standard element facts + language fact + pattern fact
	factCount := len(facts)
	if factCount == 0 {
		t.Errorf("Expected facts to be emitted")
	}

	foundElementFact := false
	foundLangFact := false
	foundPatternFact := false

	for _, f := range facts {
		if f.Predicate == "code_element" {
			foundElementFact = true
		} else if f.Predicate == "lang_fact" {
			foundLangFact = true
		} else if f.Predicate == "generated_code" {
			foundPatternFact = true
		}
	}

	if !foundElementFact { t.Errorf("Missing element fact") }
	if !foundLangFact { t.Errorf("Missing language fact") }
	if !foundPatternFact { t.Errorf("Missing pattern fact") }
}

func TestParserFactory_SupportedExtensions(t *testing.T) {
	factory := NewParserFactory("/")
	factory.Register(&mockParser{extensions: []string{".a", ".b"}})
	factory.Register(&mockParser{extensions: []string{".c"}})

	exts := factory.SupportedExtensions()
	sort.Strings(exts)

	if len(exts) != 3 || exts[0] != ".a" || exts[1] != ".b" || exts[2] != ".c" {
		t.Errorf("Unexpected extensions: %v", exts)
	}
}

func TestParserFactory_RegisteredLanguages(t *testing.T) {
	factory := NewParserFactory("/")
	factory.Register(&mockParser{language: "l1", extensions: []string{".a"}})
	factory.Register(&mockParser{language: "l2", extensions: []string{".b"}})
	factory.Register(&mockParser{language: "l1", extensions: []string{".c"}}) // Duplicate language

	langs := factory.RegisteredLanguages()
	sort.Strings(langs)

	if len(langs) != 2 || langs[0] != "l1" || langs[1] != "l2" {
		t.Errorf("Unexpected languages: %v", langs)
	}
}

func TestParserFactory_RelativePath(t *testing.T) {
	factory := NewParserFactory("/root/project")

	// Test normal case
	rel := factory.RelativePath("/root/project/src/file.go")
	expected := "src/file.go"
	if filepath.ToSlash(rel) != expected {
		t.Errorf("Expected %s, got %s", expected, filepath.ToSlash(rel))
	}

	// Test unrelated path (should return absolute)
	rel = factory.RelativePath("/other/path/file.go")
	// On Windows, RelativePath across volumes might fail differently, but the fallback should be absolute
	if rel != "../../other/path/file.go" {
		t.Errorf("Expected ../../other/path/file.go for unrelated directory, got %s", rel)
	}
}

func TestDefaultParserFactory(t *testing.T) {
	// Creating default parser should not panic and should register standard parsers
	factory := DefaultParserFactory("/")

	if len(factory.parsers) == 0 {
		t.Errorf("Expected parsers to be registered")
	}

	// Spot check a few known extensions
	if !factory.HasParser(".go") {
		t.Errorf("Expected .go parser to be registered")
	}
	if !factory.HasParser(".py") {
		t.Errorf("Expected .py parser to be registered")
	}
	if !factory.HasParser(".ts") {
		t.Errorf("Expected .ts parser to be registered")
	}
	if !factory.HasParser(".rs") {
		t.Errorf("Expected .rs parser to be registered")
	}
	if !factory.HasParser(".dl") {
		t.Errorf("Expected .dl (mangle) parser to be registered")
	}
}
