package world

import (
	"codenerd/internal/core"
	"errors"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
)

// mockCodeParser implements CodeParser for testing purposes.
type mockCodeParser struct {
	lang       string
	extensions []string
	parseFunc  func(path string, content []byte) ([]CodeElement, error)
	factsFunc  func(elements []CodeElement) []core.Fact
}

func (m *mockCodeParser) Parse(path string, content []byte) ([]CodeElement, error) {
	if m.parseFunc != nil {
		return m.parseFunc(path, content)
	}
	return nil, nil
}

func (m *mockCodeParser) SupportedExtensions() []string {
	return m.extensions
}

func (m *mockCodeParser) EmitLanguageFacts(elements []CodeElement) []core.Fact {
	if m.factsFunc != nil {
		return m.factsFunc(elements)
	}
	return nil
}

func (m *mockCodeParser) Language() string {
	return m.lang
}

func TestNewParserFactory(t *testing.T) {
	projectRoot := "/test/project"
	factory := NewParserFactory(projectRoot)

	if factory.ProjectRoot() != projectRoot {
		t.Errorf("Expected project root %s, got %s", projectRoot, factory.ProjectRoot())
	}

	if factory.parsers == nil {
		t.Error("Expected parsers map to be initialized")
	}
}

func TestParserFactory_Register_GetParser_HasParser(t *testing.T) {
	factory := NewParserFactory("/test")

	// Mock parser for .test1 and .test2 extensions
	mockParser1 := &mockCodeParser{
		lang:       "testlang1",
		extensions: []string{".test1", "test2"}, // test2 lacks dot to test normalization
	}

	factory.Register(mockParser1)

	// Check HasParser
	if !factory.HasParser("file.test1") {
		t.Error("Expected factory to have parser for .test1")
	}
	if !factory.HasParser("file.test2") {
		t.Error("Expected factory to have parser for .test2 (normalized)")
	}
	if factory.HasParser("file.test3") {
		t.Error("Expected factory to NOT have parser for .test3")
	}

	// Check GetParser
	p1 := factory.GetParser("file.test1")
	if p1 != mockParser1 {
		t.Errorf("Expected mockParser1 for .test1, got %v", p1)
	}

	p2 := factory.GetParser("file.TEST2") // case insensitivity check
	if p2 != mockParser1 {
		t.Errorf("Expected mockParser1 for .TEST2, got %v", p2)
	}

	p3 := factory.GetParser("file.test3")
	if p3 != nil {
		t.Errorf("Expected nil for .test3, got %v", p3)
	}
}

func TestParserFactory_Parse_Basic(t *testing.T) {
	factory := NewParserFactory("/test")
	expectedElements := []CodeElement{
		{Type: "/function", Name: "testFunc"},
	}

	mockParser := &mockCodeParser{
		lang:       "testlang",
		extensions: []string{".test"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			return expectedElements, nil
		},
	}
	factory.Register(mockParser)

	// Test successful parse
	elements, err := factory.Parse("file.test", []byte("content"))
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	if !reflect.DeepEqual(elements, expectedElements) {
		t.Errorf("Expected elements %v, got %v", expectedElements, elements)
	}

	// Test parse failure (no parser)
	_, err = factory.Parse("file.unknown", []byte("content"))
	if err == nil {
		t.Error("Expected error when no parser registered")
	}
	if err.Error() != "no parser registered for extension: .unknown" {
		t.Errorf("Unexpected error message: %v", err)
	}
}

func TestParserFactory_ParseWithFacts(t *testing.T) {
	factory := NewParserFactory("/test")
	expectedElements := []CodeElement{
		{Type: "/function", Name: "testFunc"},
	}
	expectedLangFacts := []core.Fact{
		{Predicate: "test_fact", Args: []interface{}{"arg1"}},
	}
	expectedErr := errors.New("parse error")

	mockParser := &mockCodeParser{
		lang:       "testlang",
		extensions: []string{".test"},
		parseFunc: func(path string, content []byte) ([]CodeElement, error) {
			if path == "error.test" {
				return nil, expectedErr
			}
			return expectedElements, nil
		},
		factsFunc: func(elements []CodeElement) []core.Fact {
			return expectedLangFacts
		},
	}
	factory.Register(mockParser)

	// Test successful parse
	content := "// Code generated by protoc\ntest content"
	result, err := factory.ParseWithFacts("file.test", []byte(content))
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	if !reflect.DeepEqual(result.Elements, expectedElements) {
		t.Errorf("Expected elements %v, got %v", expectedElements, result.Elements)
	}
	if !reflect.DeepEqual(result.LanguageFacts, expectedLangFacts) {
		t.Errorf("Expected lang facts %v, got %v", expectedLangFacts, result.LanguageFacts)
	}
	if !result.Patterns.IsGenerated {
		t.Error("Expected patterns to detect generated code")
	}

	// Test parse failure (no parser)
	_, err = factory.ParseWithFacts("file.unknown", []byte("content"))
	if err == nil {
		t.Error("Expected error when no parser registered")
	}

	// Test parse error returned from parser
	_, err = factory.ParseWithFacts("error.test", []byte("content"))
	if err != expectedErr {
		t.Errorf("Expected error %v, got %v", expectedErr, err)
	}
}

func TestParserFactory_EmitAllFacts(t *testing.T) {
	factory := NewParserFactory("/test")

	// Create mock ParseResult
	elem := CodeElement{
		Type: "/function",
		Ref: "testRef",
	}
	langFact := core.Fact{Predicate: "test_fact", Args: []interface{}{"arg1"}}
	patterns := CodePatterns{IsGenerated: true}

	result := &ParseResult{
		Elements: []CodeElement{elem},
		LanguageFacts: []core.Fact{langFact},
		Patterns: patterns,
	}

	facts := factory.EmitAllFacts(result, "file.test")

	// Verify we have element facts + language facts + pattern facts
	// CodeElement.ToFacts() emits at least 2 facts (is_code_element, code_element_type)
	// CodePatterns.ToPatternFacts() emits at least 1 fact (is_generated) when IsGenerated is true
	if len(facts) < 4 {
		t.Errorf("Expected at least 4 facts, got %d", len(facts))
	}

	// Check if our specific language fact is present
	foundLangFact := false
	for _, f := range facts {
		if f.Predicate == "test_fact" {
			foundLangFact = true
			break
		}
	}
	if !foundLangFact {
		t.Error("Language fact not emitted")
	}
}

func TestParserFactory_SupportedExtensions_RegisteredLanguages(t *testing.T) {
	factory := NewParserFactory("/test")

	mockParser1 := &mockCodeParser{
		lang:       "lang1",
		extensions: []string{".ext1", ".ext2"},
	}
	mockParser2 := &mockCodeParser{
		lang:       "lang2",
		extensions: []string{".ext3"},
	}

	factory.Register(mockParser1)
	factory.Register(mockParser2)

	exts := factory.SupportedExtensions()
	sort.Strings(exts)
	expectedExts := []string{".ext1", ".ext2", ".ext3"}
	if !reflect.DeepEqual(exts, expectedExts) {
		t.Errorf("Expected extensions %v, got %v", expectedExts, exts)
	}

	langs := factory.RegisteredLanguages()
	sort.Strings(langs)
	expectedLangs := []string{"lang1", "lang2"}
	if !reflect.DeepEqual(langs, expectedLangs) {
		t.Errorf("Expected languages %v, got %v", expectedLangs, langs)
	}
}

func TestParserFactory_RelativePath(t *testing.T) {
	projectRoot := "/home/user/project"
	factory := NewParserFactory(projectRoot)

	absPath := filepath.Join(projectRoot, "src", "main.go")

	relPath := factory.RelativePath(absPath)

	// Should normalize to forward slashes
	expected := "src/main.go"
	if relPath != expected {
		t.Errorf("Expected %s, got %s", expected, relPath)
	}

	// Test invalid relative path (should fallback to absolute)
	// Using a completely unrelated path
	unrelatedPath := "/tmp/other"
	relUnrelated := factory.RelativePath(unrelatedPath)

	// This might actually succeed depending on OS (e.g. returning ../../../tmp/other)
	// Let's just make sure it returns a string and doesn't panic
	if relUnrelated == "" {
		t.Error("Expected some string for relative path fallback")
	}
}

func TestNormalizeExtension(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{".go", ".go"},
		{"go", ".go"},
		{".GO", ".go"},
		{"GO", ".go"},
		{"", "."},
	}

	for _, tt := range tests {
		result := normalizeExtension(tt.input)
		if result != tt.expected {
			t.Errorf("normalizeExtension(%q) = %q, expected %q", tt.input, result, tt.expected)
		}
	}
}

func TestDefaultParserFactory(t *testing.T) {
	factory := DefaultParserFactory("/test")

	// Check if built-in parsers are registered
	langs := factory.RegisteredLanguages()

	// We expect go, mangle, python, typescript, rust
	expectedLangs := map[string]bool{
		"go": false,
		"mg": false,
		"py": false,
		"ts": false,
		"rs": false,
	}

	for _, l := range langs {
		if _, ok := expectedLangs[l]; ok {
			expectedLangs[l] = true
		}
	}

	for lang, found := range expectedLangs {
		if !found {
			t.Errorf("Default factory missing parser for language: %s", lang)
		}
	}
}
