package world

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"codenerd/internal/types"
)

// The CodeDOM scope keeps absolute paths for I/O but every fact it emits must
// carry the canonical identity, or none of the rules that join
// active_file/file_in_scope/code_element against file_topology, code_defines
// or modified can fire (codedom_core.mg, codedom_edit.mg, reviewer.mg,
// test_impact.mg).

// scopePathArgIndexes names the argument slots that carry a file identity in
// the scope family's predicates.
var scopePathArgIndexes = map[string][]int{
	"active_file":          {0},
	"file_in_scope":        {0},
	"code_element":         {2},
	"generated_code":       {0},
	"cgo_code":             {0},
	"build_tag":            {0},
	"embed_directive":      {0},
	"large_file_warning":   {0},
	"encoding_issue":       {0},
	"parse_error":          {0},
	"file_not_found":       {0},
	"scope_refresh_failed": {0},
	"file_hash_mismatch":   {0},
}

func TestFileScope_ScopeFacts_ShouldCarryCanonicalPaths(t *testing.T) {
	root := t.TempDir()
	write := func(rel, content string) string {
		full := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return full
	}
	write("go.mod", "module example.com/ws\n\ngo 1.22\n")
	main := write("internal/a/a.go", "package a\n\n// Code generated by tool; DO NOT EDIT.\n\nfunc Run() int { return helper() }\n")
	write("internal/a/b.go", "package a\n\nfunc helper() int { return 1 }\n")

	scope := NewFileScope(root)
	if err := scope.Open(main); err != nil {
		t.Fatalf("Open: %v", err)
	}
	facts := scope.ScopeFacts()
	if len(facts) == 0 {
		t.Fatal("no scope facts")
	}

	seen := map[string]int{}
	for _, f := range facts {
		idxs, ok := scopePathArgIndexes[f.Predicate]
		if !ok {
			continue
		}
		seen[f.Predicate]++
		for _, i := range idxs {
			if i >= len(f.Args) {
				t.Errorf("%s has %d args, expected a path at %d", f.Predicate, len(f.Args), i)
				continue
			}
			p, _ := f.Args[i].(string)
			if p == "" || filepath.IsAbs(p) || strings.Contains(p, `\`) || strings.Contains(p, root) || types.SlashClean(p) != p {
				t.Errorf("%s carries non-canonical path %q in %v", f.Predicate, p, f.Args)
			}
		}
	}
	for _, want := range []string{"active_file", "file_in_scope", "code_element", "generated_code"} {
		if seen[want] == 0 {
			t.Errorf("no %s fact was emitted; predicates seen: %v", want, seen)
		}
	}
	var active string
	for _, f := range facts {
		if f.Predicate == "active_file" {
			active, _ = f.Args[0].(string)
		}
	}
	if active != "internal/a/a.go" {
		t.Errorf("active_file = %q, want internal/a/a.go", active)
	}

	// The scope still opens files through its absolute state, and accepts the
	// canonical identity coming back from a fact.
	if !scope.IsInScope("internal/a/a.go") || !scope.IsInScope(main) {
		t.Error("IsInScope must accept both the canonical identity and the absolute path")
	}
	if len(scope.GetCoreElementsByFile("internal/a/a.go")) == 0 {
		t.Error("GetCoreElementsByFile must resolve a canonical identity against the project root")
	}
	if ok, err := scope.VerifyFileHash("internal/a/a.go"); err != nil || !ok {
		t.Errorf("VerifyFileHash(canonical) = %v, %v; want unchanged", ok, err)
	}
	for _, p := range scope.GetInScopeFiles() {
		if !filepath.IsAbs(p) {
			t.Errorf("GetInScopeFiles must stay absolute for I/O, got %q", p)
		}
	}
}
