// Package defaults provides embedded default resources for codeNERD.
// These resources are compiled into the binary for zero-dependency startup.
package defaults

import "embed"

// IntentCorpusDB contains the pre-built intent classification corpus.
// This database is built during the CI/CD pipeline and embedded at compile time.
// The corpus contains canonical intent patterns with their embeddings for
// fast semantic classification of user inputs.
//
// Usage:
//
//	data, err := IntentCorpusDB.ReadFile("intent_corpus.db")
//	if err != nil {
//	    // Handle missing corpus (development mode)
//	}
//
// NOTE: The embed pattern uses a wildcard to allow the build to succeed
// even when the corpus database hasn't been generated yet. In development,
// the corpus is generated by running: go run ./cmd/tools/corpus_builder
//
//go:embed intent_corpus.db*
//go:embed intent_corpus.db.placeholder
var IntentCorpusDB embed.FS
