// Package defaults provides embedded default resources for codeNERD.
// These resources are compiled into the binary for zero-dependency startup.
package defaults

import "embed"

// PromptCorpusDB contains the pre-built prompt atom corpus for JIT compilation.
// This database is built during the CI/CD pipeline and embedded at compile time.
// The corpus contains prompt atoms with their embeddings for dynamic prompt assembly.
//
// Usage:
//
//	data, err := PromptCorpusDB.ReadFile("prompt_corpus.db")
//	if err != nil {
//	    // Handle missing corpus (development mode)
//	}
//
// NOTE: The embed pattern uses a wildcard to allow the build to succeed
// even when the corpus database hasn't been generated yet. In development,
// the corpus is generated by running: go run ./cmd/tools/prompt_builder
//
//go:embed prompt_corpus.db*
//go:embed prompt_corpus.db.placeholder
var PromptCorpusDB embed.FS

// PromptCorpusAvailable returns true if the embedded corpus is available.
// During development, the corpus may not exist until built.
func PromptCorpusAvailable() bool {
	entries, err := PromptCorpusDB.ReadDir(".")
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.Name() == "prompt_corpus.db" {
			return true
		}
	}
	return false
}
