# =============================================================================
# codeNERD Log Analysis Schema
# Embedded in logquery tool for declarative log debugging
# =============================================================================
#
# Simplified schema - aggregations removed due to builtin compatibility
# Facts are generated by parse_log.py and loaded at runtime.
#
# Usage:
#   1. Generate facts: python parse_log.py .nerd/logs/*.log > facts.mg
#   2. Query: logquery facts.mg --builtin errors
#   3. REPL: logquery facts.mg -i
#
# =============================================================================

# =============================================================================
# SECTION 1: CORE EDB DECLARATIONS
# =============================================================================

# Primary log entry fact - generated by parse_log.py
# log_entry(Timestamp_ms, Category, Level, Message, Filename, LineNumber)
Decl log_entry(Time, Category, Level, Message, File, Line).

# =============================================================================
# SECTION 2: LEVEL FILTER PREDICATES
# =============================================================================

# Error entries only
Decl error_entry(Time, Category, Message).
error_entry(T, C, M) :- log_entry(T, C, /error, M, _, _).

# Warning entries only
Decl warning_entry(Time, Category, Message).
warning_entry(T, C, M) :- log_entry(T, C, /warn, M, _, _).

# Info entries only
Decl info_entry(Time, Category, Message).
info_entry(T, C, M) :- log_entry(T, C, /info, M, _, _).

# Debug entries only
Decl debug_entry(Time, Category, Message).
debug_entry(T, C, M) :- log_entry(T, C, /debug, M, _, _).

# =============================================================================
# SECTION 3: CATEGORY PREDICATES
# =============================================================================

# Category event stream
Decl category_event(Category, Time, Level).
category_event(C, T, L) :- log_entry(T, C, L, _, _, _).

# Categories with entries
Decl active_category(Category).
active_category(C) :- log_entry(_, C, _, _, _, _).

# Categories with errors
Decl error_category(Category).
error_category(C) :- error_entry(_, C, _).

# Categories with warnings
Decl warning_category(Category).
warning_category(C) :- warning_entry(_, C, _).

# =============================================================================
# SECTION 4: CORRELATION PREDICATES (disabled for large datasets)
# =============================================================================

# NOTE: Correlation predicates cause N^2 explosion with large datasets.
# Uncomment for small fact sets (<10K entries).

# Events correlated within time window (100ms)
# Decl correlated(Time1, Cat1, Time2, Cat2).
# correlated(T1, C1, T2, C2) :-
#     log_entry(T1, C1, _, _, _, _),
#     log_entry(T2, C2, _, _, _, _),
#     C1 != C2,
#     T2 > T1,
#     fn:minus(T2, T1) < 100.

# Strongly correlated (within 50ms)
# Decl strongly_correlated(Time1, Cat1, Time2, Cat2).
# strongly_correlated(T1, C1, T2, C2) :-
#     log_entry(T1, C1, _, _, _, _),
#     log_entry(T2, C2, _, _, _, _),
#     C1 != C2,
#     T2 > T1,
#     fn:minus(T2, T1) < 50.

# =============================================================================
# SECTION 5: ERROR ANALYSIS PREDICATES (most disabled for large datasets)
# =============================================================================

# NOTE: Error cascade/context predicates cause O(errors^2) explosion.
# With many errors in logs, these become prohibitively expensive.

# Error cascade detection - DISABLED
# Decl error_cascade(Error1Time, Error1Cat, Error2Time, Error2Cat).
# error_cascade(E1T, E1C, E2T, E2C) :-
#     error_entry(E1T, E1C, _),
#     error_entry(E2T, E2C, _),
#     E2T > E1T,
#     fn:minus(E2T, E1T) < 100.

# Root cause - DISABLED (requires error_cascade)
# Decl root_cause(Time, Category, Message).
# root_cause(T, C, M) :-
#     error_entry(T, C, M),
#     !error_cascade(_, _, T, C).

# Error context - DISABLED
# Decl error_context(ErrorTime, ErrorCat, PriorTime, PriorCat, PriorMsg).
# error_context(ET, EC, PT, PC, PM) :-
#     error_entry(ET, EC, _),
#     log_entry(PT, PC, _, PM, _, _),
#     PT < ET,
#     fn:minus(ET, PT) < 500.

# =============================================================================
# SECTION 6: EXECUTION FLOW PREDICATES (disabled for large datasets)
# =============================================================================

# NOTE: Flow predicates cause O(n^2) explosion. Disabled by default.
# Decl flow_edge(FromCat, ToCat, Time).
# flow_edge(C1, C2, T2) :-
#     log_entry(T1, C1, _, _, _, _),
#     log_entry(T2, C2, _, _, _, _),
#     C1 != C2,
#     T2 > T1,
#     fn:minus(T2, T1) < 50.

# Decl reachable(FromCat, ToCat).
# reachable(C1, C2) :- flow_edge(C1, C2, _).
# reachable(C1, C3) :- flow_edge(C1, C2, _), reachable(C2, C3).

# =============================================================================
# SECTION 7: ANOMALY DETECTION (disabled for large datasets)
# =============================================================================

# NOTE: Event gaps cause O(n^2) explosion. Disabled by default.
# Decl event_gap(Time1, Cat1, Time2, Cat2, GapMs).
# event_gap(T1, C1, T2, C2, Gap) :-
#     log_entry(T1, C1, _, _, _, _),
#     log_entry(T2, C2, _, _, _, _),
#     T2 > T1,
#     Gap = fn:minus(T2, T1),
#     Gap > 5000.

# =============================================================================
# SECTION 8: CATEGORY-SPECIFIC EVENT PREDICATES
# =============================================================================

# Kernel events
Decl kernel_event(Time, Level, Message).
kernel_event(T, L, M) :- log_entry(T, /kernel, L, M, _, _).

# Shard events (general)
Decl shard_event(Time, Level, Message).
shard_event(T, L, M) :- log_entry(T, /shards, L, M, _, _).

# Perception events
Decl perception_event(Time, Level, Message).
perception_event(T, L, M) :- log_entry(T, /perception, L, M, _, _).

# Articulation events
Decl articulation_event(Time, Level, Message).
articulation_event(T, L, M) :- log_entry(T, /articulation, L, M, _, _).

# API events
Decl api_event(Time, Level, Message).
api_event(T, L, M) :- log_entry(T, /api, L, M, _, _).

# Campaign events
Decl campaign_event(Time, Level, Message).
campaign_event(T, L, M) :- log_entry(T, /campaign, L, M, _, _).

# Session events
Decl session_event(Time, Level, Message).
session_event(T, L, M) :- log_entry(T, /session, L, M, _, _).

# Boot events
Decl boot_event(Time, Level, Message).
boot_event(T, L, M) :- log_entry(T, /boot, L, M, _, _).

# Tools events
Decl tools_event(Time, Level, Message).
tools_event(T, L, M) :- log_entry(T, /tools, L, M, _, _).

# Routing events
Decl routing_event(Time, Level, Message).
routing_event(T, L, M) :- log_entry(T, /routing, L, M, _, _).

# Store events
Decl store_event(Time, Level, Message).
store_event(T, L, M) :- log_entry(T, /store, L, M, _, _).

# Virtual store events
Decl virtual_store_event(Time, Level, Message).
virtual_store_event(T, L, M) :- log_entry(T, /virtual_store, L, M, _, _).

# World/filesystem events
Decl world_event(Time, Level, Message).
world_event(T, L, M) :- log_entry(T, /world, L, M, _, _).

# Autopoiesis events
Decl autopoiesis_event(Time, Level, Message).
autopoiesis_event(T, L, M) :- log_entry(T, /autopoiesis, L, M, _, _).

# Researcher shard events
Decl researcher_event(Time, Level, Message).
researcher_event(T, L, M) :- log_entry(T, /researcher, L, M, _, _).

# Reviewer shard events
Decl reviewer_event(Time, Level, Message).
reviewer_event(T, L, M) :- log_entry(T, /reviewer, L, M, _, _).

# Context compression events
Decl context_event(Time, Level, Message).
context_event(T, L, M) :- log_entry(T, /context, L, M, _, _).

# Embedding events
Decl embedding_event(Time, Level, Message).
embedding_event(T, L, M) :- log_entry(T, /embedding, L, M, _, _).

# System shards events
Decl system_shards_event(Time, Level, Message).
system_shards_event(T, L, M) :- log_entry(T, /system_shards, L, M, _, _).

# Coder shard events
Decl coder_event(Time, Level, Message).
coder_event(T, L, M) :- log_entry(T, /coder, L, M, _, _).

# Tester shard events
Decl tester_event(Time, Level, Message).
tester_event(T, L, M) :- log_entry(T, /tester, L, M, _, _).

# Dream state events
Decl dream_event(Time, Level, Message).
dream_event(T, L, M) :- log_entry(T, /dream, L, M, _, _).

# Browser automation events
Decl browser_event(Time, Level, Message).
browser_event(T, L, M) :- log_entry(T, /browser, L, M, _, _).

# Tactile/command execution events
Decl tactile_event(Time, Level, Message).
tactile_event(T, L, M) :- log_entry(T, /tactile, L, M, _, _).

# =============================================================================
# SECTION 9: ERROR-SPECIFIC PREDICATES BY CATEGORY
# =============================================================================

# Shard errors
Decl shard_error(Time, Message).
shard_error(T, M) :- log_entry(T, /shards, /error, M, _, _).

# Kernel errors
Decl kernel_error(Time, Message).
kernel_error(T, M) :- log_entry(T, /kernel, /error, M, _, _).

# Kernel debug
Decl kernel_debug(Time, Message).
kernel_debug(T, M) :- log_entry(T, /kernel, /debug, M, _, _).

# API errors
Decl api_error(Time, Message).
api_error(T, M) :- log_entry(T, /api, /error, M, _, _).

# API warnings
Decl api_warning(Time, Message).
api_warning(T, M) :- log_entry(T, /api, /warn, M, _, _).

# Perception errors
Decl perception_error(Time, Message).
perception_error(T, M) :- log_entry(T, /perception, /error, M, _, _).

# Articulation errors
Decl articulation_error(Time, Message).
articulation_error(T, M) :- log_entry(T, /articulation, /error, M, _, _).

# Session errors
Decl session_error(Time, Message).
session_error(T, M) :- log_entry(T, /session, /error, M, _, _).

# Boot errors
Decl boot_error(Time, Message).
boot_error(T, M) :- log_entry(T, /boot, /error, M, _, _).

# Campaign errors
Decl campaign_error(Time, Message).
campaign_error(T, M) :- log_entry(T, /campaign, /error, M, _, _).

# Tools errors
Decl tools_error(Time, Message).
tools_error(T, M) :- log_entry(T, /tools, /error, M, _, _).

# Routing errors
Decl routing_error(Time, Message).
routing_error(T, M) :- log_entry(T, /routing, /error, M, _, _).

# Store errors
Decl store_error(Time, Message).
store_error(T, M) :- log_entry(T, /store, /error, M, _, _).

# Virtual store errors
Decl virtual_store_error(Time, Message).
virtual_store_error(T, M) :- log_entry(T, /virtual_store, /error, M, _, _).

# World errors
Decl world_error(Time, Message).
world_error(T, M) :- log_entry(T, /world, /error, M, _, _).

# Autopoiesis errors
Decl autopoiesis_error(Time, Message).
autopoiesis_error(T, M) :- log_entry(T, /autopoiesis, /error, M, _, _).

# Researcher errors
Decl researcher_error(Time, Message).
researcher_error(T, M) :- log_entry(T, /researcher, /error, M, _, _).

# Reviewer errors
Decl reviewer_error(Time, Message).
reviewer_error(T, M) :- log_entry(T, /reviewer, /error, M, _, _).

# Context errors
Decl context_error(Time, Message).
context_error(T, M) :- log_entry(T, /context, /error, M, _, _).

# Embedding errors
Decl embedding_error(Time, Message).
embedding_error(T, M) :- log_entry(T, /embedding, /error, M, _, _).

# System shards errors
Decl system_shards_error(Time, Message).
system_shards_error(T, M) :- log_entry(T, /system_shards, /error, M, _, _).

# Coder errors
Decl coder_error(Time, Message).
coder_error(T, M) :- log_entry(T, /coder, /error, M, _, _).

# Tester errors
Decl tester_error(Time, Message).
tester_error(T, M) :- log_entry(T, /tester, /error, M, _, _).

# Dream errors
Decl dream_error(Time, Message).
dream_error(T, M) :- log_entry(T, /dream, /error, M, _, _).

# Browser errors
Decl browser_error(Time, Message).
browser_error(T, M) :- log_entry(T, /browser, /error, M, _, _).

# Tactile errors
Decl tactile_error(Time, Message).
tactile_error(T, M) :- log_entry(T, /tactile, /error, M, _, _).

# =============================================================================
# END OF SCHEMA
# =============================================================================
