package campaign

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"codenerd/internal/core"
	"codenerd/internal/session"
)

// A coder turn stopped by its obligations must not reach the repository by
// another road. Campaign 1284b6bb (2026-09-19): the coder was stopped with
// "hollow success blocked: turn created Go source ... without a test file",
// and executeFileTask fell back to asking the model to "Generate the following
// file" -- a write that carries none of the turn's obligations (tests,
// coverage, vet, verdict). It was refused only because the stopped turn had
// already written the file. The fallback generates documents; for anything
// else a coder failure fails the task, and the task's error leads with the
// coder's reason, which is what the retry and the replanner read.

// fallbackGateFixture wires a real kernel and VirtualStore, so a fallback
// write that is not refused really lands, and a coder that always fails with
// coderErr. generated counts the model's direct-generation calls.
func fallbackGateFixture(t *testing.T, coderErr error) (o *Orchestrator, root string, generated *int) {
	t.Helper()
	root = t.TempDir()
	k, err := core.NewRealKernel()
	if err != nil {
		t.Fatal(err)
	}
	cfg := core.DefaultVirtualStoreConfig()
	cfg.WorkingDir = root
	vs := core.NewVirtualStoreWithConfig(&mockTactileExecutor{}, cfg)
	t.Cleanup(func() { vs.Close() })
	vs.SetKernel(k)
	vs.DisableBootGuard()
	generated = new(int)
	o = &Orchestrator{
		campaign:     &Campaign{ID: "/campaign_fallback_gate"},
		workspace:    root,
		kernel:       k,
		virtualStore: vs,
		llmClient: &MockLLMClient{CompleteFunc: func(context.Context, string) (string, error) {
			*generated++
			return "generated by the fallback\n", nil
		}},
		taskExecutor: &MockTaskExecutor{ExecuteFunc: func(context.Context, session.TaskRequest) (string, error) {
			return "", coderErr
		}},
	}
	return o, root, generated
}

func TestFileTask_CoderStoppedOnCodeFailsTheTaskWithItsReason(t *testing.T) {
	coderErr := errors.New("execution failed: hollow success blocked: turn created Go source internal/x/checker.go without a test file (verb /fix)")
	o, root, generated := fallbackGateFixture(t, coderErr)
	task := &Task{ID: "/task_gate_code", Type: TaskTypeFileCreate, Description: "Create the checker", WriteSet: []string{"internal/x/checker.go"}}

	_, err := o.executeFileTask(context.Background(), task)
	if err == nil {
		t.Fatal("a coder failure on code must fail the task")
	}
	if *generated != 0 {
		t.Fatalf("the model was asked %d time(s) to generate code outside the coder's turn", *generated)
	}
	if _, statErr := os.Stat(filepath.Join(root, "internal", "x", "checker.go")); statErr == nil {
		t.Fatal("code reached the workspace through the fallback")
	}
	if !errors.Is(err, coderErr) {
		t.Fatalf("the task's error must carry the coder's reason, got: %v", err)
	}
	if i, j := strings.Index(err.Error(), "hollow success blocked"), strings.Index(err.Error(), "fallback"); i < 0 || (j >= 0 && j < i) {
		t.Fatalf("the coder's reason must lead the task's error, not follow the fallback's refusal: %v", err)
	}
}

// The refusal of an existing target (the one that fired in 1284b6bb) keeps the
// coder's reason too: that refusal is not why the work stopped.
func TestFileTask_RefusalOverAnExistingTargetKeepsTheCodersReason(t *testing.T) {
	coderErr := errors.New("execution failed: hollow success blocked: turn created Go source internal/x/checker.go without a test file (verb /fix)")
	o, root, generated := fallbackGateFixture(t, coderErr)
	full := filepath.Join(root, "internal", "x", "checker.go")
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte("package x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	task := &Task{ID: "/task_gate_existing", Type: TaskTypeFileCreate, Description: "Create the checker", WriteSet: []string{"internal/x/checker.go"}}

	_, err := o.executeFileTask(context.Background(), task)
	if err == nil || !errors.Is(err, coderErr) {
		t.Fatalf("the task's error must carry the coder's reason, got: %v", err)
	}
	if *generated != 0 {
		t.Fatalf("the model was asked %d time(s) to generate a file that exists", *generated)
	}
}

// Documents are what the fallback is for (F-DOC-1, F-TASK-1): a deliverable
// whose shard failed is still generated and written through the VirtualStore.
// Until 2026-09-19 it never was: the fallback asserted a pending_action whose
// payload ({"content_bytes":N}) the kernel's permission check, which matches the
// exact routed payload, could not match, so every fallback write was refused
// after the model had generated it. This is also the fixture's control: the
// store does accept writes, so the code test's missing file is the refusal, not
// the store.
func TestFileTask_CoderFailureOnADocumentStillFallsBack(t *testing.T) {
	o, root, generated := fallbackGateFixture(t, errors.New("coder explored without writing"))
	task := &Task{ID: "/task_gate_doc", Type: TaskTypeFileCreate, Description: "Write the report", WriteSet: []string{"docs/report.md"}}

	if _, err := o.executeFileTask(context.Background(), task); err != nil {
		t.Fatalf("a document deliverable still falls back to direct generation: %v", err)
	}
	if *generated != 1 {
		t.Fatalf("expected one direct-generation call for the document, got %d", *generated)
	}
	data, err := os.ReadFile(filepath.Join(root, "docs", "report.md"))
	if err != nil || !strings.Contains(string(data), "generated by the fallback") {
		t.Fatalf("the document was not written through the VirtualStore: %q, %v", data, err)
	}
}

// A generated document over the action payload cap is refused, as the session
// executor refuses one: permitted/3 is matched against the exact payload, so a
// truncated one could never be permitted, and an oversized one is never
// asserted into the kernel.
func TestFileTask_FallbackDocumentOverThePayloadCapIsRefused(t *testing.T) {
	o, root, generated := fallbackGateFixture(t, errors.New("coder explored without writing"))
	o.llmClient = &MockLLMClient{CompleteFunc: func(context.Context, string) (string, error) {
		*generated++
		// Distinct words per line: a report the degenerate-output guard
		// (isDegenerateGeneration) takes for prose, so it reaches the cap
		// instead of being replaced by the short placeholder.
		var b strings.Builder
		for i := 0; b.Len() <= session.MaxActionPayloadBytes; i++ {
			fmt.Fprintf(&b, "Finding item%dx concerns module%dx and path%dx.\n", i, i*7, i*13)
		}
		return b.String(), nil
	}}
	task := &Task{ID: "/task_gate_big", Type: TaskTypeFileCreate, Description: "Write the report", WriteSet: []string{"docs/big.md"}}

	_, err := o.executeFileTask(context.Background(), task)
	if err == nil || !strings.Contains(err.Error(), "action payload cap") {
		t.Fatalf("an over-cap document must be refused naming the cap, got %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(root, "docs", "big.md")); statErr == nil {
		t.Fatal("an over-cap document was written")
	}
}
